#ifndef ARDUINO

#include "wled_host_cli.h"

#include <cstdlib>
#include <ostream>
#include <string>

#ifndef WLED_HOST_PRODUCT_NAME
  #define WLED_HOST_PRODUCT_NAME "WLED"
#endif

#ifndef WLED_HOST_VERSION
  #define WLED_HOST_VERSION "dev"
#endif

namespace {

const char* kProductName = WLED_HOST_PRODUCT_NAME;
const char* kVersionString = WLED_HOST_VERSION;

bool requiresValue(const std::string& arg) {
  return arg == "--config-dir" || arg == "--host" || arg == "--port" || arg == "--log-level" || arg == "--resolve-path" || arg == "--read-file" || arg == "--copy-file" ||
         arg == "--rename-file" || arg == "--delete-file" || arg == "--compare-files" || arg == "--validate-json" || arg == "--dump-json" || arg == "--dump-route" ||
         arg == "--apply-settings" || arg == "--apply-json" || arg == "--stage-update-file" ||
         arg == "--backup-file" || arg == "--restore-file" ||
         arg == "--has-backup" || arg == "--blend-color" || arg == "--add-color" || arg == "--fade-color" || arg == "--prng-seq" || arg == "--playlist-run" || arg == "--preset-name" ||
         arg == "--delete-preset";
}

bool assignOptionValue(HostCliOptions& options, const std::string& arg, const std::string& value, std::string& error) {
  if (arg == "--config-dir") {
    options.configDir = value;
    return true;
  }
  if (arg == "--host") {
    options.host = value;
    return true;
  }
  if (arg == "--log-level") {
    options.logLevel = value;
    return true;
  }
  if (arg == "--resolve-path") {
    options.resolvePath = value;
    return true;
  }
  if (arg == "--read-file") {
    options.readPath = value;
    return true;
  }
  if (arg == "--copy-file") {
    options.copyPathSpec = value;
    return true;
  }
  if (arg == "--rename-file") {
    options.renamePathSpec = value;
    return true;
  }
  if (arg == "--delete-file") {
    options.deletePath = value;
    return true;
  }
  if (arg == "--compare-files") {
    options.comparePathSpec = value;
    return true;
  }
  if (arg == "--validate-json") {
    options.validatePath = value;
    return true;
  }
  if (arg == "--dump-json") {
    options.dumpJsonTarget = value;
    return true;
  }
  if (arg == "--dump-route") {
    options.dumpRouteTarget = value;
    return true;
  }
  if (arg == "--apply-settings") {
    options.applySettingsSpec = value;
    return true;
  }
  if (arg == "--apply-json") {
    options.applyJsonSpec = value;
    return true;
  }
  if (arg == "--stage-update-file") {
    options.stageUpdateFile = value;
    return true;
  }
  if (arg == "--backup-file") {
    options.backupPath = value;
    return true;
  }
  if (arg == "--restore-file") {
    options.restorePath = value;
    return true;
  }
  if (arg == "--has-backup") {
    options.hasBackupPath = value;
    return true;
  }
  if (arg == "--blend-color") {
    options.blendColorSpec = value;
    return true;
  }
  if (arg == "--add-color") {
    options.addColorSpec = value;
    return true;
  }
  if (arg == "--fade-color") {
    options.fadeColorSpec = value;
    return true;
  }
  if (arg == "--prng-seq") {
    options.prngSequenceSpec = value;
    return true;
  }
  if (arg == "--playlist-run") {
    options.playlistRunSpec = value;
    return true;
  }
  if (arg == "--preset-name") {
    options.presetNameSpec = value;
    return true;
  }
  if (arg == "--delete-preset") {
    options.deletePresetSpec = value;
    return true;
  }
  if (arg == "--port") {
    char* end = nullptr;
    const long parsedPort = std::strtol(value.c_str(), &end, 10);
    if (!end || *end != '\0' || parsedPort < 0 || parsedPort > 65535) {
      error = "Invalid value for --port: " + value;
      return false;
    }
    options.port = static_cast<int>(parsedPort);
    return true;
  }

  error = "Unknown option: " + arg;
  return false;
}

} // namespace

// AI: below section was generated by an AI
HostCliParseResult parseHostCliArgs(int argc, char** argv) {
  HostCliParseResult result;

  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];

    if (arg == "--help") {
      result.options.showHelp = true;
      continue;
    }
    if (arg == "--version") {
      result.options.showVersion = true;
      continue;
    }
    if (arg == "--exit-after-bootstrap") {
      result.options.exitAfterBootstrap = true;
      continue;
    }
    if (arg == "--list-files") {
      result.options.listFiles = true;
      continue;
    }
    if (arg == "--init-presets") {
      result.options.initPresets = true;
      continue;
    }
    if (arg == "--backup-config") {
      result.options.backupConfig = true;
      continue;
    }
    if (arg == "--restore-config") {
      result.options.restoreConfig = true;
      continue;
    }
    if (arg == "--verify-config") {
      result.options.verifyConfig = true;
      continue;
    }
    if (arg == "--reset-config") {
      result.options.resetConfig = true;
      continue;
    }
    if (arg == "--has-config-backup") {
      result.options.hasConfigBackup = true;
      continue;
    }
    if (arg == "--verify-secrets") {
      result.options.verifySecrets = true;
      continue;
    }
    if (arg.rfind("--", 0) == 0) {
      if (!requiresValue(arg)) {
        result.ok = false;
        result.error = "Unknown option: " + arg;
        return result;
      }
      if (i + 1 >= argc) {
        result.ok = false;
        result.error = "Missing value for option: " + arg;
        return result;
      }
      if (!assignOptionValue(result.options, arg, argv[++i], result.error)) {
        result.ok = false;
        return result;
      }
      continue;
    }

    result.options.positionalArgs.emplace_back(arg);
  }

  return result;
}
// AI: end

void printHostCliHelp(std::ostream& out) {
  out
    << "WLED native host runtime\n"
    << "Usage: WLED [options]\n"
    << "Executable: wled-native\n\n"
    << "Options:\n"
    << "  --help                Show this help text and exit\n"
    << "  --version             Show the WLED version and exit\n"
    << "  --config-dir <path>   Override the configuration directory\n"
    << "  --exit-after-bootstrap Print runtime bootstrap details and exit without serving\n"
    << "  --host <address>      Bind address for the native server (default: 127.0.0.1)\n"
    << "  --port <number>       Bind port for the native server (use 0 for an ephemeral port)\n"
    << "  --log-level <level>   Set the runtime log level\n"
    << "  --resolve-path <path> Resolve a WLED logical file path inside the config root\n\n"
    << "  --read-file <path>    Read a WLED logical file path inside the config root\n"
    << "  --copy-file <a:b>     Copy one WLED logical file path to another inside the config root\n\n"
    << "  --rename-file <a:b>   Rename one WLED logical file path to another inside the config root\n"
    << "  --delete-file <path>  Delete a WLED logical file path inside the config root\n\n"
    << "  --compare-files <a:b> Compare two WLED logical file paths inside the config root\n"
    << "  --validate-json <p>   Validate a WLED logical JSON file inside the config root\n"
    << "  --dump-json <name>    Print native JSON payload for one of: info, state, si, all, effects, palettes, pal, palx[:page], live, cfg, net, pins, nodes\n"
    << "  --dump-route <path>   Render one native GET route body without starting the server\n"
    << "  --apply-settings <p:b> Apply a WLED form post body b to settings path p without starting the server\n"
    << "  --apply-json <p:b>    Apply a WLED JSON POST body b to JSON path p without starting the server\n"
    << "  --stage-update-file <path> Stage one native package/update artifact inside the config root\n"
    << "  --backup-file <path>  Create a WLED backup file named bkp.<path>\n"
    << "  --restore-file <path> Restore a WLED backup file named bkp.<path>\n"
    << "  --has-backup <path>   Check whether a WLED backup file named bkp.<path> exists\n"
    << "  --list-files          List JSON files in the config root except secrets files\n"
    << "  --blend-color <a:b:n> Blend two hex colors with WLED color_blend() using blend 0-255\n"
    << "  --add-color <a:b[:p]> Add two hex colors with WLED color_add() and optional preserve-ratio flag 0/1\n"
    << "  --fade-color <c:n[:v]> Fade one hex color with WLED color_fade() using amount 0-255 and optional video flag 0/1\n"
    << "  --prng-seq <s:n>      Emit n PRNG values from seed s using WLED prng.h\n\n"
    << "  --playlist-run <p:s:t> Load a playlist JSON file from the config root, run s ticks, and advance t ms per tick\n\n"
    << "  --init-presets        Recreate presets.json with the original WLED bootstrap object if it is missing\n"
    << "  --preset-name <id>    Read preset id from presets.json using original preset-file logic\n"
    << "  --delete-preset <id>  Clear preset id from presets.json using original preset-file logic\n\n"
    << "  --backup-config       Create a backup for cfg.json using original config helpers\n"
    << "  --restore-config      Restore cfg.json from its backup using original config helpers\n"
    << "  --verify-config       Validate cfg.json using original config helpers\n"
    << "  --reset-config        Rename cfg.json to rst.cfg.json using original config helpers\n"
    << "  --has-config-backup   Check whether cfg.json has a backup using original config helpers\n"
    << "  --verify-secrets      Validate wsec.json using original config helpers\n\n"
    << "Config directory priority:\n"
    << "  1. --config-dir\n"
    << "  2. WLED_CONFIG_DIR\n"
    << "  3. Platform default (macOS: ~/Library/Application Support/WLED, Linux: $XDG_CONFIG_HOME/wled or ~/.config/wled)\n";
}

void printHostCliVersion(std::ostream& out) {
  out << kProductName << ' ' << kVersionString << '\n';
}

#endif // !ARDUINO
