#ifndef ARDUINO

#include "wled_host_core.h"

#include <algorithm>
#include <cstdlib>
#include <cstring>

namespace {

std::mt19937& hostRandomGenerator() {
  static std::mt19937 generator(std::random_device{}());
  return generator;
}

} // namespace

uint32_t hw_random() {
  return hostRandomGenerator()();
}

uint32_t hw_random(uint32_t upperlimit) {
  if (upperlimit == 0) return 0;
  const uint64_t scaled = static_cast<uint64_t>(hw_random()) * static_cast<uint64_t>(upperlimit);
  return static_cast<uint32_t>(scaled >> 32);
}

int32_t hw_random(int32_t lowerlimit, int32_t upperlimit) {
  if (lowerlimit >= upperlimit) return lowerlimit;
  const uint32_t diff = static_cast<uint32_t>(upperlimit - lowerlimit);
  return lowerlimit + static_cast<int32_t>(hw_random(diff));
}

uint8_t get_random_wheel_index(uint8_t pos) {
  uint8_t candidate = 0;
  uint8_t leftDistance = 0;
  uint8_t rightDistance = 0;
  uint8_t minDistance = 0;
  while (minDistance < 42) {
    candidate = hw_random8();
    leftDistance = static_cast<uint8_t>(std::abs(static_cast<int>(pos) - static_cast<int>(candidate)));
    rightDistance = static_cast<uint8_t>(255 - leftDistance);
    minDistance = std::min(leftDistance, rightDistance);
  }
  return candidate;
}

// AI: below section was generated by an AI
uint32_t color_blend(uint32_t color1, uint32_t color2, uint8_t blend) {
  const uint32_t twoChannelMask = 0x00FF00FF;
  const uint32_t rb1 = color1 & twoChannelMask;
  const uint32_t wg1 = (color1 >> 8) & twoChannelMask;
  const uint32_t rb2 = color2 & twoChannelMask;
  const uint32_t wg2 = (color2 >> 8) & twoChannelMask;
  const uint32_t rb3 = ((((rb1 << 8) | rb2) + (rb2 * blend) - (rb1 * blend)) >> 8) & twoChannelMask;
  const uint32_t wg3 = ((((wg1 << 8) | wg2) + (wg2 * blend) - (wg1 * blend))) & ~twoChannelMask;
  return rb3 | wg3;
}

uint32_t color_fade(uint32_t color, uint8_t amount, bool video) {
  if (color == BLACK || amount == 0) return 0;
  if (amount == 255) return color;

  const uint32_t twoChannelMask = 0x00FF00FF;
  const uint32_t rb = color & twoChannelMask;
  const uint32_t wg = (color >> 8) & twoChannelMask;
  uint32_t rbScaled = 0;
  uint32_t wgScaled = 0;

  if (video) {
    rbScaled = ((rb * amount + 0x007F007F) >> 8) & twoChannelMask;
    wgScaled = (wg * amount + 0x007F007F) & ~twoChannelMask;

    const uint8_t r = static_cast<uint8_t>(rb >> 16);
    const uint8_t g = static_cast<uint8_t>(wg);
    const uint8_t b = static_cast<uint8_t>(rb);
    const uint8_t w = static_cast<uint8_t>(wg >> 16);
    uint8_t maxChannel = std::max(r, g);
    maxChannel = std::max(maxChannel, b);
    maxChannel = std::max(maxChannel, w);
    maxChannel = static_cast<uint8_t>((maxChannel >> 2) + 1);

    rbScaled |= r > maxChannel ? 0x00010000 : 0;
    wgScaled |= g > maxChannel ? 0x00000100 : 0;
    rbScaled |= b > maxChannel ? 0x00000001 : 0;
    wgScaled |= w ? 0x01000000 : 0;
  } else {
    rbScaled = ((rb * (amount + 1U)) >> 8) & twoChannelMask;
    wgScaled = (wg * (amount + 1U)) & ~twoChannelMask;
  }

  return rbScaled | wgScaled;
}

bool colorFromHexString(byte* rgb, const char* in) {
  if (rgb == nullptr || in == nullptr) return false;
  const size_t inputSize = strnlen(in, 9);
  if (inputSize != 6U && inputSize != 8U) return false;

  const uint32_t color = static_cast<uint32_t>(std::strtoul(in, nullptr, 16));
  rgb[0] = inputSize == 6U ? static_cast<byte>(color >> 16) : static_cast<byte>(color >> 24);
  rgb[1] = inputSize == 6U ? static_cast<byte>(color >> 8) : static_cast<byte>(color >> 16);
  rgb[2] = inputSize == 6U ? static_cast<byte>(color) : static_cast<byte>(color >> 8);
  rgb[3] = inputSize == 8U ? static_cast<byte>(color) : 0;
  return true;
}
// AI: end

#endif // !ARDUINO
