#ifndef ARDUINO

#include "wled_host_cli.h"

#include <iostream>

// AI: below section was generated by an AI
int main(int argc, char** argv) {
  const HostCliParseResult parseResult = parseHostCliArgs(argc, argv);
  if (!parseResult.ok) {
    std::cerr << parseResult.error << '\n' << '\n';
    printHostCliHelp(std::cerr);
    return 1;
  }

  if (parseResult.options.showHelp) {
    printHostCliHelp(std::cout);
    return 0;
  }

  if (parseResult.options.showVersion) {
    printHostCliVersion(std::cout);
    return 0;
  }

  std::cout
    << "WLED host bootstrap is not implemented yet.\n"
    << "Prepared CLI settings:\n"
    << "  host: " << parseResult.options.host << '\n'
    << "  port: " << parseResult.options.port << '\n'
    << "  log-level: " << parseResult.options.logLevel << '\n'
    << "  config-dir: "
    << (parseResult.options.configDir.empty() ? "<default>" : parseResult.options.configDir)
    << '\n';

  return 0;
}
// AI: end

#endif // !ARDUINO
