#ifndef ARDUINO

#include "wled_host_cli.h"

#include <cstdlib>
#include <ostream>
#include <string>

#ifndef WLED_HOST_PRODUCT_NAME
  #define WLED_HOST_PRODUCT_NAME "WLED"
#endif

#ifndef WLED_HOST_VERSION
  #define WLED_HOST_VERSION "dev"
#endif

namespace {

const char* kProductName = WLED_HOST_PRODUCT_NAME;
const char* kVersionString = WLED_HOST_VERSION;

bool requiresValue(const std::string& arg) {
  return arg == "--config-dir" || arg == "--host" || arg == "--port" || arg == "--log-level";
}

bool assignOptionValue(HostCliOptions& options, const std::string& arg, const std::string& value, std::string& error) {
  if (arg == "--config-dir") {
    options.configDir = value;
    return true;
  }
  if (arg == "--host") {
    options.host = value;
    return true;
  }
  if (arg == "--log-level") {
    options.logLevel = value;
    return true;
  }
  if (arg == "--port") {
    char* end = nullptr;
    const long parsedPort = std::strtol(value.c_str(), &end, 10);
    if (!end || *end != '\0' || parsedPort < 1 || parsedPort > 65535) {
      error = "Invalid value for --port: " + value;
      return false;
    }
    options.port = static_cast<int>(parsedPort);
    return true;
  }

  error = "Unknown option: " + arg;
  return false;
}

} // namespace

// AI: below section was generated by an AI
HostCliParseResult parseHostCliArgs(int argc, char** argv) {
  HostCliParseResult result;

  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];

    if (arg == "--help") {
      result.options.showHelp = true;
      continue;
    }
    if (arg == "--version") {
      result.options.showVersion = true;
      continue;
    }
    if (arg.rfind("--", 0) == 0) {
      if (!requiresValue(arg)) {
        result.ok = false;
        result.error = "Unknown option: " + arg;
        return result;
      }
      if (i + 1 >= argc) {
        result.ok = false;
        result.error = "Missing value for option: " + arg;
        return result;
      }
      if (!assignOptionValue(result.options, arg, argv[++i], result.error)) {
        result.ok = false;
        return result;
      }
      continue;
    }

    result.options.positionalArgs.emplace_back(arg);
  }

  return result;
}
// AI: end

void printHostCliHelp(std::ostream& out) {
  out
    << "WLED host bootstrap CLI\n"
    << "Usage: WLED [options]\n"
    << "Executable: wled-native\n\n"
    << "Options:\n"
    << "  --help                Show this help text and exit\n"
    << "  --version             Show the WLED version and exit\n"
    << "  --config-dir <path>   Override the configuration directory\n"
    << "  --host <address>      Bind address for the future native server\n"
    << "  --port <number>       Bind port for the future native server\n"
    << "  --log-level <level>   Set the bootstrap log level\n";
}

void printHostCliVersion(std::ostream& out) {
  out << kProductName << ' ' << kVersionString << '\n';
}

#endif // !ARDUINO
