#ifndef ARDUINO

#include "wled_host_storage.h"

#include <array>
#include <cctype>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <random>
#include <set>
#include <sstream>
#include <vector>

namespace {

constexpr const char* kInstanceIdFileName = "instance-id";
constexpr const char* kCfgJsonFileName = "cfg.json";
constexpr const char* kWsecJsonFileName = "wsec.json";
constexpr const char* kPresetsJsonFileName = "presets.json";
constexpr const char* kTempPresetJsonFileName = "tmp.json";

constexpr const char* kEmptyObjectJson = "{}\n";
constexpr const char* kPresetBootstrapJson = "{\"0\":{}}\n";

const HostStorageLayout* activeHostStorageLayout = nullptr;

const char* getEnvironmentVariable(const char* name) {
  const char* value = std::getenv(name);
  return (value && value[0] != '\0') ? value : nullptr;
}

std::filesystem::path getHomeDirectory() {
  if (const char* home = getEnvironmentVariable("HOME")) return home;
  return std::filesystem::current_path();
}

std::filesystem::path getDefaultConfigDirectory() {
  const std::filesystem::path homeDirectory = getHomeDirectory();

#ifdef __APPLE__
  return homeDirectory / "Library" / "Application Support" / "WLED";
#else
  if (const char* xdgConfigHome = getEnvironmentVariable("XDG_CONFIG_HOME")) {
    return std::filesystem::path(xdgConfigHome) / "wled";
  }
  return homeDirectory / ".config" / "wled";
#endif
}

bool isHexByte(char first, char second) {
  return std::isxdigit(static_cast<unsigned char>(first)) && std::isxdigit(static_cast<unsigned char>(second));
}

bool isValidInstanceId(const std::string& instanceId) {
  if (instanceId.size() != 17U) return false;

  for (size_t i = 0; i < instanceId.size(); ++i) {
    if ((i % 3U) == 2U) {
      if (instanceId[i] != ':') return false;
      continue;
    }
    if (!std::isxdigit(static_cast<unsigned char>(instanceId[i]))) return false;
  }

  for (size_t i = 0; i < instanceId.size(); i += 3U) {
    if (!isHexByte(instanceId[i], instanceId[i + 1U])) return false;
  }

  return true;
}

std::string generateInstanceId() {
  std::random_device randomDevice;
  std::mt19937 generator(randomDevice());
  std::uniform_int_distribution<unsigned> distribution(0U, 255U);
  std::array<uint8_t, 6> bytes{};

  for (uint8_t& value : bytes) value = static_cast<uint8_t>(distribution(generator));

  bytes[0] = static_cast<uint8_t>((bytes[0] | 0x02U) & 0xFEU); // locally administered, unicast

  std::ostringstream output;
  output << std::uppercase << std::hex << std::setfill('0');
  for (size_t i = 0; i < bytes.size(); ++i) {
    if (i) output << ':';
    output << std::setw(2) << static_cast<unsigned>(bytes[i]);
  }
  return output.str();
}

bool readTextFile(const std::filesystem::path& filePath, std::string& value) {
  std::ifstream input(filePath);
  if (!input.is_open()) return false;

  std::getline(input, value);
  return !value.empty();
}

bool writeTextFile(const std::filesystem::path& filePath, const std::string& value, std::string& error) {
  std::ofstream output(filePath, std::ios::trunc);
  if (!output.is_open()) {
    error = "Unable to open file for writing: " + filePath.string();
    return false;
  }

  output << value;
  if (!output.good()) {
    error = "Unable to persist runtime state to: " + filePath.string();
    return false;
  }

  return true;
}

bool ensureFileExists(const std::filesystem::path& filePath, const char* bootstrapContents, std::string& error) {
  if (std::filesystem::exists(filePath)) return true;
  return writeTextFile(filePath, bootstrapContents, error);
}

bool ensureInstanceId(const std::filesystem::path& filePath, std::string& instanceId, std::string& error) {
  if (readTextFile(filePath, instanceId) && isValidInstanceId(instanceId)) return true;

  instanceId = generateInstanceId();
  return writeTextFile(filePath, instanceId + '\n', error);
}

std::string makeBackupLogicalPath(const std::string& logicalPath) {
  std::string trimmedPath = logicalPath;
  while (!trimmedPath.empty() && trimmedPath.front() == '/') trimmedPath.erase(trimmedPath.begin());
  return "bkp." + trimmedPath;
}

// AI: below section was generated by an AI
class JsonValidator {
public:
  explicit JsonValidator(const std::string& input) : _input(input) {}

  bool isValid() {
    skipWhitespace();
    if (!parseValue()) return false;
    skipWhitespace();
    return _position == _input.size();
  }

private:
  const std::string& _input;
  size_t _position = 0;

  void skipWhitespace() {
    while (_position < _input.size() && std::isspace(static_cast<unsigned char>(_input[_position]))) ++_position;
  }

  bool parseValue() {
    if (_position >= _input.size()) return false;

    const char current = _input[_position];
    if (current == '{') return parseObject();
    if (current == '[') return parseArray();
    if (current == '"') return parseString();
    if (current == '-' || std::isdigit(static_cast<unsigned char>(current))) return parseNumber();
    if (_input.compare(_position, 4, "true") == 0) {
      _position += 4;
      return true;
    }
    if (_input.compare(_position, 5, "false") == 0) {
      _position += 5;
      return true;
    }
    if (_input.compare(_position, 4, "null") == 0) {
      _position += 4;
      return true;
    }
    return false;
  }

  bool parseObject() {
    ++_position;
    skipWhitespace();
    if (_position < _input.size() && _input[_position] == '}') {
      ++_position;
      return true;
    }

    while (_position < _input.size()) {
      if (!parseString()) return false;
      skipWhitespace();
      if (_position >= _input.size() || _input[_position] != ':') return false;
      ++_position;
      skipWhitespace();
      if (!parseValue()) return false;
      skipWhitespace();
      if (_position >= _input.size()) return false;
      if (_input[_position] == '}') {
        ++_position;
        return true;
      }
      if (_input[_position] != ',') return false;
      ++_position;
      skipWhitespace();
    }

    return false;
  }

  bool parseArray() {
    ++_position;
    skipWhitespace();
    if (_position < _input.size() && _input[_position] == ']') {
      ++_position;
      return true;
    }

    while (_position < _input.size()) {
      if (!parseValue()) return false;
      skipWhitespace();
      if (_position >= _input.size()) return false;
      if (_input[_position] == ']') {
        ++_position;
        return true;
      }
      if (_input[_position] != ',') return false;
      ++_position;
      skipWhitespace();
    }

    return false;
  }

  bool parseString() {
    if (_position >= _input.size() || _input[_position] != '"') return false;
    ++_position;

    while (_position < _input.size()) {
      const char current = _input[_position++];
      if (current == '"') return true;
      if (static_cast<unsigned char>(current) < 0x20U) return false;
      if (current != '\\') continue;
      if (_position >= _input.size()) return false;

      const char escaped = _input[_position++];
      if (escaped == 'u') {
        for (int i = 0; i < 4; ++i) {
          if (_position >= _input.size() || !std::isxdigit(static_cast<unsigned char>(_input[_position++]))) return false;
        }
        continue;
      }

      switch (escaped) {
        case '"':
        case '\\':
        case '/':
        case 'b':
        case 'f':
        case 'n':
        case 'r':
        case 't':
          break;
        default:
          return false;
      }
    }

    return false;
  }

  bool parseNumber() {
    const size_t start = _position;

    if (_input[_position] == '-') ++_position;
    if (_position >= _input.size()) return false;

    if (_input[_position] == '0') {
      ++_position;
    } else {
      if (!std::isdigit(static_cast<unsigned char>(_input[_position]))) return false;
      while (_position < _input.size() && std::isdigit(static_cast<unsigned char>(_input[_position]))) ++_position;
    }

    if (_position < _input.size() && _input[_position] == '.') {
      ++_position;
      if (_position >= _input.size() || !std::isdigit(static_cast<unsigned char>(_input[_position]))) return false;
      while (_position < _input.size() && std::isdigit(static_cast<unsigned char>(_input[_position]))) ++_position;
    }

    if (_position < _input.size() && (_input[_position] == 'e' || _input[_position] == 'E')) {
      ++_position;
      if (_position < _input.size() && (_input[_position] == '+' || _input[_position] == '-')) ++_position;
      if (_position >= _input.size() || !std::isdigit(static_cast<unsigned char>(_input[_position]))) return false;
      while (_position < _input.size() && std::isdigit(static_cast<unsigned char>(_input[_position]))) ++_position;
    }

    return _position > start;
  }
};
// AI: end

} // namespace

void setActiveHostStorageLayout(const HostStorageLayout* layout) {
  activeHostStorageLayout = layout;
}

const HostStorageLayout* getActiveHostStorageLayout() {
  return activeHostStorageLayout;
}

std::filesystem::path resolveHostConfigDirectory(const std::string& cliOverride) {
  if (!cliOverride.empty()) return std::filesystem::path(cliOverride);
  if (const char* configDir = getEnvironmentVariable("WLED_CONFIG_DIR")) return std::filesystem::path(configDir);
  return getDefaultConfigDirectory();
}

HostStorageLayout buildHostStorageLayout(const std::filesystem::path& configDir) {
  const std::filesystem::path normalizedConfigDir = std::filesystem::absolute(configDir).lexically_normal();
  return {
    normalizedConfigDir,
    normalizedConfigDir / kInstanceIdFileName,
    normalizedConfigDir / kCfgJsonFileName,
    normalizedConfigDir / kWsecJsonFileName,
    normalizedConfigDir / kPresetsJsonFileName,
    normalizedConfigDir / kTempPresetJsonFileName,
  };
}

// AI: below section was generated by an AI
bool bootstrapHostStorage(const HostStorageLayout& layout, std::string& instanceId, std::string& error) {
  std::error_code filesystemError;
  std::filesystem::create_directories(layout.configDir, filesystemError);
  if (filesystemError) {
    error = "Unable to create configuration directory '" + layout.configDir.string() + "': " + filesystemError.message();
    return false;
  }

  if (!ensureInstanceId(layout.instanceIdFile, instanceId, error)) return false;
  if (!ensureFileExists(layout.cfgFile, kEmptyObjectJson, error)) return false;
  if (!ensureFileExists(layout.wsecFile, kEmptyObjectJson, error)) return false;
  if (!ensureFileExists(layout.presetsFile, kPresetBootstrapJson, error)) return false;
  if (!ensureFileExists(layout.tempPresetFile, kPresetBootstrapJson, error)) return false;

  return true;
}

bool resolveHostStoragePath(const HostStorageLayout& layout, const std::string& logicalPath, std::filesystem::path& resolvedPath, std::string& error) {
  if (logicalPath.empty()) {
    error = "Logical path must not be empty.";
    return false;
  }

  std::string trimmedPath = logicalPath;
  while (!trimmedPath.empty() && trimmedPath.front() == '/') trimmedPath.erase(trimmedPath.begin());
  if (trimmedPath.empty()) {
    error = "Logical path must target a file inside the config root.";
    return false;
  }

  const std::filesystem::path relativePath(trimmedPath);
  if (relativePath.is_absolute()) {
    error = "Absolute path escapes are not allowed: " + logicalPath;
    return false;
  }

  for (const std::filesystem::path& component : relativePath) {
    const std::string token = component.string();
    if (token == "." || token == "..") {
      error = "Path traversal is not allowed: " + logicalPath;
      return false;
    }
  }

  resolvedPath = (layout.configDir / relativePath).lexically_normal();
  const std::string configRoot = layout.configDir.native();
  const std::string candidate = resolvedPath.native();
  const bool insideConfigRoot = candidate == configRoot ||
                                (candidate.size() > configRoot.size() &&
                                 candidate.compare(0, configRoot.size(), configRoot) == 0 &&
                                 candidate[configRoot.size()] == std::filesystem::path::preferred_separator);
  if (!insideConfigRoot) {
    error = "Resolved path escapes the config root: " + logicalPath;
    return false;
  }

  return true;
}

bool readHostStorageFile(const HostStorageLayout& layout, const std::string& logicalPath, std::string& content, std::string& error) {
  std::filesystem::path resolvedPath;
  if (!resolveHostStoragePath(layout, logicalPath, resolvedPath, error)) return false;

  std::ifstream input(resolvedPath, std::ios::binary);
  if (!input.is_open()) {
    error = "Unable to open file for reading: " + resolvedPath.string();
    return false;
  }

  std::ostringstream buffer;
  buffer << input.rdbuf();
  if (!input.good() && !input.eof()) {
    error = "Unable to read file: " + resolvedPath.string();
    return false;
  }

  content = buffer.str();
  return true;
}

bool copyHostStorageFile(const HostStorageLayout& layout, const std::string& sourceLogicalPath, const std::string& destinationLogicalPath, std::string& error) {
  std::filesystem::path sourcePath;
  std::filesystem::path destinationPath;
  if (!resolveHostStoragePath(layout, sourceLogicalPath, sourcePath, error)) return false;
  if (!resolveHostStoragePath(layout, destinationLogicalPath, destinationPath, error)) return false;

  std::error_code filesystemError;
  std::filesystem::copy_file(sourcePath, destinationPath, std::filesystem::copy_options::overwrite_existing, filesystemError);
  if (filesystemError) {
    error = "Unable to copy file from '" + sourcePath.string() + "' to '" + destinationPath.string() + "': " + filesystemError.message();
    return false;
  }

  return true;
}

bool renameHostStorageFile(const HostStorageLayout& layout, const std::string& sourceLogicalPath, const std::string& destinationLogicalPath, std::string& error) {
  std::filesystem::path sourcePath;
  std::filesystem::path destinationPath;
  if (!resolveHostStoragePath(layout, sourceLogicalPath, sourcePath, error)) return false;
  if (!resolveHostStoragePath(layout, destinationLogicalPath, destinationPath, error)) return false;

  std::error_code filesystemError;
  std::filesystem::rename(sourcePath, destinationPath, filesystemError);
  if (filesystemError) {
    error = "Unable to rename file from '" + sourcePath.string() + "' to '" + destinationPath.string() + "': " + filesystemError.message();
    return false;
  }

  return true;
}

bool deleteHostStorageFile(const HostStorageLayout& layout, const std::string& logicalPath, std::string& error) {
  std::filesystem::path resolvedPath;
  if (!resolveHostStoragePath(layout, logicalPath, resolvedPath, error)) return false;

  std::error_code filesystemError;
  const bool removed = std::filesystem::remove(resolvedPath, filesystemError);
  if (filesystemError) {
    error = "Unable to delete file '" + resolvedPath.string() + "': " + filesystemError.message();
    return false;
  }
  if (!removed) {
    error = "Unable to delete file '" + resolvedPath.string() + "': file does not exist.";
    return false;
  }

  return true;
}

bool compareHostStorageFiles(const HostStorageLayout& layout, const std::string& firstLogicalPath, const std::string& secondLogicalPath, bool& identical, std::string& error) {
  std::string firstContent;
  std::string secondContent;
  if (!readHostStorageFile(layout, firstLogicalPath, firstContent, error)) return false;
  if (!readHostStorageFile(layout, secondLogicalPath, secondContent, error)) return false;

  identical = firstContent == secondContent;
  return true;
}

bool validateHostStorageJsonFile(const HostStorageLayout& layout, const std::string& logicalPath, std::string& error) {
  std::string content;
  if (!readHostStorageFile(layout, logicalPath, content, error)) return false;

  if (JsonValidator(content).isValid()) return true;

  error = "Invalid JSON file: " + logicalPath;
  return false;
}

bool createHostStorageBackup(const HostStorageLayout& layout, const std::string& logicalPath, std::string& backupLogicalPath, std::string& error) {
  if (!validateHostStorageJsonFile(layout, logicalPath, error)) return false;

  backupLogicalPath = makeBackupLogicalPath(logicalPath);
  return copyHostStorageFile(layout, logicalPath, backupLogicalPath, error);
}

bool restoreHostStorageBackup(const HostStorageLayout& layout, const std::string& logicalPath, std::string& backupLogicalPath, std::string& error) {
  backupLogicalPath = makeBackupLogicalPath(logicalPath);
  std::filesystem::path backupPath;
  if (!resolveHostStoragePath(layout, backupLogicalPath, backupPath, error)) return false;
  if (!std::filesystem::exists(backupPath)) {
    error = "Backup missing: " + backupLogicalPath;
    return false;
  }
  if (!validateHostStorageJsonFile(layout, backupLogicalPath, error)) return false;
  return copyHostStorageFile(layout, backupLogicalPath, logicalPath, error);
}

bool hostStorageBackupExists(const HostStorageLayout& layout, const std::string& logicalPath, std::string& backupLogicalPath, std::string& error) {
  backupLogicalPath = makeBackupLogicalPath(logicalPath);
  std::filesystem::path backupPath;
  if (!resolveHostStoragePath(layout, backupLogicalPath, backupPath, error)) return false;
  if (std::filesystem::exists(backupPath)) return true;

  error = "Backup missing: " + backupLogicalPath;
  return false;
}

bool listHostStorageFiles(const HostStorageLayout& layout, std::vector<std::string>& fileNames, std::string& error) {
  std::error_code filesystemError;
  if (!std::filesystem::exists(layout.configDir, filesystemError)) {
    error = "Unable to list files inside missing config root: " + layout.configDir.string();
    return false;
  }
  if (filesystemError) {
    error = "Unable to inspect config root '" + layout.configDir.string() + "': " + filesystemError.message();
    return false;
  }

  std::set<std::string> sortedFileNames;
  for (const std::filesystem::directory_entry& entry : std::filesystem::directory_iterator(layout.configDir, filesystemError)) {
    if (filesystemError) {
      error = "Unable to iterate config root '" + layout.configDir.string() + "': " + filesystemError.message();
      return false;
    }
    if (!entry.is_regular_file()) continue;

    const std::string fileName = entry.path().filename().string();
    if (entry.path().extension() != ".json") continue;
    if (fileName.rfind("wsec", 0) == 0 || fileName.rfind("bkp.wsec", 0) == 0) continue;
    sortedFileNames.insert(fileName);
  }

  fileNames.assign(sortedFileNames.begin(), sortedFileNames.end());
  return true;
}
// AI: end

#endif // !ARDUINO
