#include "Network.h"

#include <array>
#include <chrono>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>

#if defined(__unix__) || defined(__APPLE__)
#include <arpa/inet.h>
#include <ifaddrs.h>
#include <net/if.h>
#include <netdb.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <unistd.h>
#endif

// AI: below section was generated by an AI
namespace {

uint32_t toHostOrder(const IPAddress &address) {
  return (static_cast<uint32_t>(address[0]) << 24) |
         (static_cast<uint32_t>(address[1]) << 16) |
         (static_cast<uint32_t>(address[2]) << 8) |
         static_cast<uint32_t>(address[3]);
}

IPAddress fromNetworkAddress(uint32_t networkAddress) {
  const uint32_t hostAddress = ntohl(networkAddress);
  return IPAddress(
    static_cast<uint8_t>((hostAddress >> 24) & 0xFF),
    static_cast<uint8_t>((hostAddress >> 16) & 0xFF),
    static_cast<uint8_t>((hostAddress >> 8) & 0xFF),
    static_cast<uint8_t>(hostAddress & 0xFF)
  );
}

std::string extractMacJsonValue(const std::string &json) {
  const std::string key = "\"mac\"";
  const size_t keyPos = json.find(key);
  if (keyPos == std::string::npos) return "";

  const size_t colon = json.find(':', keyPos + key.size());
  if (colon == std::string::npos) return "";

  const size_t firstQuote = json.find('"', colon + 1);
  if (firstQuote == std::string::npos) return "";

  const size_t secondQuote = json.find('"', firstQuote + 1);
  if (secondQuote == std::string::npos) return "";

  return json.substr(firstQuote + 1, secondQuote - firstQuote - 1);
}

uint64_t nativeEntropy() {
  const auto now = std::chrono::high_resolution_clock::now().time_since_epoch().count();
  const uintptr_t stackValue = reinterpret_cast<uintptr_t>(&now);
#if defined(__unix__) || defined(__APPLE__)
  const uint64_t processValue = static_cast<uint64_t>(getpid());
#else
  const uint64_t processValue = 0;
#endif
  return static_cast<uint64_t>(now) ^ (static_cast<uint64_t>(stackValue) << 7) ^ (processValue << 32);
}

} // namespace

NativeIdentityStore::NativeIdentityStore(const std::string &configDir)
  : _configDir(configDir),
    _identityPath((std::filesystem::path(configDir) / "native-id.json").string()) {
}

std::string NativeIdentityStore::loadOrCreateMac() {
  const std::string persisted = readPersistedMac();
  if (isValidMac(persisted)) return persisted;

  const std::string generated = generateMac();
  writePersistedMac(generated);
  return generated;
}

bool NativeIdentityStore::isValidMac(const std::string &mac) {
  if (mac.size() != 12) return false;
  for (char c : mac) {
    if (!std::isxdigit(static_cast<unsigned char>(c))) return false;
    if (std::isalpha(static_cast<unsigned char>(c)) && !std::islower(static_cast<unsigned char>(c))) return false;
  }

  return true;
}

std::string NativeIdentityStore::readPersistedMac() const {
  std::ifstream input(_identityPath);
  if (!input) return "";

  std::stringstream buffer;
  buffer << input.rdbuf();
  return extractMacJsonValue(buffer.str());
}

bool NativeIdentityStore::writePersistedMac(const std::string &mac) const {
  std::error_code ec;
  std::filesystem::create_directories(_configDir, ec);
  if (ec) return false;

  std::ofstream output(_identityPath, std::ios::trunc);
  if (!output) return false;

  output << "{\n  \"mac\": \"" << mac << "\"\n}\n";
  return static_cast<bool>(output);
}

std::string NativeIdentityStore::generateMac() const {
  uint64_t value = nativeEntropy();
  std::array<char, 13> mac = {};
  std::snprintf(mac.data(), mac.size(), "02%010llx", static_cast<unsigned long long>(value & 0xFFFFFFFFFFULL));
  return std::string(mac.data());
}

bool resolveHostname(const std::string &hostname, IPAddress &address) {
#if defined(__unix__) || defined(__APPLE__)
  struct addrinfo hints;
  std::memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_INET;
  hints.ai_socktype = SOCK_STREAM;

  struct addrinfo *results = nullptr;
  if (getaddrinfo(hostname.c_str(), nullptr, &hints, &results) != 0) return false;

  bool resolved = false;
  for (struct addrinfo *entry = results; entry != nullptr; entry = entry->ai_next) {
    if (entry->ai_family != AF_INET || entry->ai_addr == nullptr) continue;

    const struct sockaddr_in *addr = reinterpret_cast<const struct sockaddr_in *>(entry->ai_addr);
    address = fromNetworkAddress(addr->sin_addr.s_addr);
    resolved = true;
    break;
  }

  freeaddrinfo(results);
  return resolved;
#else
  (void)hostname;
  (void)address;
  return false;
#endif
}

std::vector<NativeNetworkInterface> listNetworkInterfaces() {
  std::vector<NativeNetworkInterface> interfaces;

#if defined(__unix__) || defined(__APPLE__)
  struct ifaddrs *ifaddr = nullptr;
  if (getifaddrs(&ifaddr) != 0) return interfaces;

  for (struct ifaddrs *ifa = ifaddr; ifa != nullptr; ifa = ifa->ifa_next) {
    if (ifa->ifa_addr == nullptr || ifa->ifa_addr->sa_family != AF_INET) continue;

    const struct sockaddr_in *addr = reinterpret_cast<const struct sockaddr_in *>(ifa->ifa_addr);
    NativeNetworkInterface iface;
    iface.name = ifa->ifa_name == nullptr ? "" : ifa->ifa_name;
    iface.address = fromNetworkAddress(addr->sin_addr.s_addr);
    iface.loopback = (ifa->ifa_flags & IFF_LOOPBACK) != 0;
    iface.up = (ifa->ifa_flags & IFF_UP) != 0;
    interfaces.push_back(iface);
  }

  freeifaddrs(ifaddr);
#endif

  return interfaces;
}

NativeUdpSocket::~NativeUdpSocket() {
  close();
}

bool NativeUdpSocket::bind(const IPAddress &address, uint16_t port) {
#if defined(__unix__) || defined(__APPLE__)
  close();
  _fd = socket(AF_INET, SOCK_DGRAM, 0);
  if (_fd < 0) return false;

  struct sockaddr_in addr;
  std::memset(&addr, 0, sizeof(addr));
  addr.sin_family = AF_INET;
  addr.sin_port = htons(port);
  addr.sin_addr.s_addr = htonl(toHostOrder(address));

  if (::bind(_fd, reinterpret_cast<struct sockaddr *>(&addr), sizeof(addr)) != 0) {
    close();
    return false;
  }

  return true;
#else
  (void)address;
  (void)port;
  return false;
#endif
}

size_t NativeUdpSocket::sendTo(const uint8_t *data, size_t size, const IPAddress &address, uint16_t port) const {
#if defined(__unix__) || defined(__APPLE__)
  if (_fd < 0 || data == nullptr) return 0;

  struct sockaddr_in addr;
  std::memset(&addr, 0, sizeof(addr));
  addr.sin_family = AF_INET;
  addr.sin_port = htons(port);
  addr.sin_addr.s_addr = htonl(toHostOrder(address));

  const ssize_t sent = sendto(_fd, data, size, 0, reinterpret_cast<struct sockaddr *>(&addr), sizeof(addr));
  return sent < 0 ? 0 : static_cast<size_t>(sent);
#else
  (void)data;
  (void)size;
  (void)address;
  (void)port;
  return 0;
#endif
}

int NativeUdpSocket::receive(uint8_t *buffer, size_t size, IPAddress &remoteAddress, uint16_t &remotePort, int timeoutMs) const {
#if defined(__unix__) || defined(__APPLE__)
  if (_fd < 0 || buffer == nullptr || size == 0) return -1;

  fd_set readSet;
  FD_ZERO(&readSet);
  FD_SET(_fd, &readSet);

  struct timeval timeout;
  timeout.tv_sec = timeoutMs / 1000;
  timeout.tv_usec = (timeoutMs % 1000) * 1000;

  const int ready = select(_fd + 1, &readSet, nullptr, nullptr, timeoutMs >= 0 ? &timeout : nullptr);
  if (ready <= 0) return ready;

  struct sockaddr_in remote;
  socklen_t remoteSize = sizeof(remote);
  const ssize_t received = recvfrom(_fd, buffer, size, 0, reinterpret_cast<struct sockaddr *>(&remote), &remoteSize);
  if (received < 0) return -1;

  remoteAddress = fromNetworkAddress(remote.sin_addr.s_addr);
  remotePort = ntohs(remote.sin_port);
  return static_cast<int>(received);
#else
  (void)buffer;
  (void)size;
  (void)remoteAddress;
  (void)remotePort;
  (void)timeoutMs;
  return -1;
#endif
}

uint16_t NativeUdpSocket::localPort() const {
#if defined(__unix__) || defined(__APPLE__)
  if (_fd < 0) return 0;

  struct sockaddr_in addr;
  socklen_t addrSize = sizeof(addr);
  if (getsockname(_fd, reinterpret_cast<struct sockaddr *>(&addr), &addrSize) != 0) return 0;

  return ntohs(addr.sin_port);
#else
  return 0;
#endif
}

void NativeUdpSocket::close() {
#if defined(__unix__) || defined(__APPLE__)
  if (_fd >= 0) {
    ::close(_fd);
    _fd = -1;
  }
#endif
}
// AI: end
