#include "NativeHttpServer.h"

#include "../arduino_compat/Arduino.h"

#include <algorithm>
#include <arpa/inet.h>
#include <array>
#include <cerrno>
#include <chrono>
#include <cctype>
#include <cstring>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <netinet/in.h>
#include <sstream>
#include <sys/socket.h>
#include <unistd.h>
#include <vector>

#ifndef WLED_NATIVE_VERSION
#define WLED_NATIVE_VERSION "dev"
#endif

// AI: below section was generated by an AI
namespace {

constexpr uint32_t SHA1_BLOCK_BYTES = 64;
constexpr uint32_t SHA1_DIGEST_BYTES = 20;
constexpr uint64_t MAX_HTTP_REQUEST_BYTES = 1024 * 1024;

struct HttpRequest {
  std::string method;
  std::string path;
  std::map<std::string, std::string> headers;
  std::string body;
};

uint32_t leftRotate(uint32_t value, uint32_t bits) {
  return (value << bits) | (value >> (32 - bits));
}

std::array<uint8_t, SHA1_DIGEST_BYTES> sha1(const std::string &input) {
  std::vector<uint8_t> data(input.begin(), input.end());
  const uint64_t bitLength = static_cast<uint64_t>(data.size()) * 8;
  data.push_back(0x80);
  while ((data.size() % SHA1_BLOCK_BYTES) != 56) data.push_back(0);
  for (int i = 7; i >= 0; i--) data.push_back(static_cast<uint8_t>((bitLength >> (i * 8)) & 0xFF));

  uint32_t h0 = 0x67452301;
  uint32_t h1 = 0xEFCDAB89;
  uint32_t h2 = 0x98BADCFE;
  uint32_t h3 = 0x10325476;
  uint32_t h4 = 0xC3D2E1F0;

  for (size_t offset = 0; offset < data.size(); offset += SHA1_BLOCK_BYTES) {
    uint32_t w[80] = {};
    for (size_t i = 0; i < 16; i++) {
      const size_t base = offset + i * 4;
      w[i] = (static_cast<uint32_t>(data[base]) << 24) |
             (static_cast<uint32_t>(data[base + 1]) << 16) |
             (static_cast<uint32_t>(data[base + 2]) << 8) |
             data[base + 3];
    }
    for (size_t i = 16; i < 80; i++) w[i] = leftRotate(w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16], 1);

    uint32_t a = h0;
    uint32_t b = h1;
    uint32_t c = h2;
    uint32_t d = h3;
    uint32_t e = h4;

    for (size_t i = 0; i < 80; i++) {
      uint32_t f = 0;
      uint32_t k = 0;
      if (i < 20) {
        f = (b & c) | ((~b) & d);
        k = 0x5A827999;
      } else if (i < 40) {
        f = b ^ c ^ d;
        k = 0x6ED9EBA1;
      } else if (i < 60) {
        f = (b & c) | (b & d) | (c & d);
        k = 0x8F1BBCDC;
      } else {
        f = b ^ c ^ d;
        k = 0xCA62C1D6;
      }
      const uint32_t temp = leftRotate(a, 5) + f + e + k + w[i];
      e = d;
      d = c;
      c = leftRotate(b, 30);
      b = a;
      a = temp;
    }

    h0 += a;
    h1 += b;
    h2 += c;
    h3 += d;
    h4 += e;
  }

  std::array<uint8_t, SHA1_DIGEST_BYTES> digest{};
  const uint32_t words[5] = {h0, h1, h2, h3, h4};
  for (size_t i = 0; i < 5; i++) {
    digest[i * 4] = static_cast<uint8_t>((words[i] >> 24) & 0xFF);
    digest[i * 4 + 1] = static_cast<uint8_t>((words[i] >> 16) & 0xFF);
    digest[i * 4 + 2] = static_cast<uint8_t>((words[i] >> 8) & 0xFF);
    digest[i * 4 + 3] = static_cast<uint8_t>(words[i] & 0xFF);
  }
  return digest;
}

std::string base64(const uint8_t *data, size_t length) {
  static constexpr char alphabet[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  std::string encoded;
  encoded.reserve(((length + 2) / 3) * 4);
  for (size_t i = 0; i < length; i += 3) {
    const uint32_t octetA = data[i];
    const uint32_t octetB = (i + 1 < length) ? data[i + 1] : 0;
    const uint32_t octetC = (i + 2 < length) ? data[i + 2] : 0;
    const uint32_t triple = (octetA << 16) | (octetB << 8) | octetC;
    encoded.push_back(alphabet[(triple >> 18) & 0x3F]);
    encoded.push_back(alphabet[(triple >> 12) & 0x3F]);
    encoded.push_back((i + 1 < length) ? alphabet[(triple >> 6) & 0x3F] : '=');
    encoded.push_back((i + 2 < length) ? alphabet[triple & 0x3F] : '=');
  }
  return encoded;
}

std::string websocketAccept(const std::string &key) {
  const std::string magic = key + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
  const std::array<uint8_t, SHA1_DIGEST_BYTES> digest = sha1(magic);
  return base64(digest.data(), digest.size());
}

std::string lower(std::string value) {
  std::transform(value.begin(), value.end(), value.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
  return value;
}

std::string trim(const std::string &value) {
  const size_t first = value.find_first_not_of(" \t\r\n");
  if (first == std::string::npos) return "";
  const size_t last = value.find_last_not_of(" \t\r\n");
  return value.substr(first, last - first + 1);
}

bool sendAll(int fd, const char *data, size_t length) {
  size_t sent = 0;
  while (sent < length) {
#ifdef MSG_NOSIGNAL
    const ssize_t result = send(fd, data + sent, length - sent, MSG_NOSIGNAL);
#else
    const ssize_t result = send(fd, data + sent, length - sent, 0);
#endif
    if (result <= 0) return false;
    sent += static_cast<size_t>(result);
  }
  return true;
}

bool sendAll(int fd, const std::string &data) {
  return sendAll(fd, data.data(), data.size());
}

std::string contentTypeFor(const std::filesystem::path &path) {
  const std::string extension = lower(path.extension().string());
  if (extension == ".htm" || extension == ".html") return "text/html; charset=utf-8";
  if (extension == ".js") return "application/javascript; charset=utf-8";
  if (extension == ".css") return "text/css; charset=utf-8";
  if (extension == ".json") return "application/json; charset=utf-8";
  if (extension == ".ico") return "image/x-icon";
  if (extension == ".png") return "image/png";
  if (extension == ".gif") return "image/gif";
  return "application/octet-stream";
}

std::string httpStatusText(int status) {
  switch (status) {
    case 101: return "Switching Protocols";
    case 200: return "OK";
    case 400: return "Bad Request";
    case 404: return "Not Found";
    case 405: return "Method Not Allowed";
    case 410: return "Gone";
    case 500: return "Internal Server Error";
    case 501: return "Not Implemented";
    default: return "OK";
  }
}

bool sendHttp(int fd, int status, const std::string &contentType, const std::string &body) {
  std::ostringstream response;
  response << "HTTP/1.1 " << status << " " << httpStatusText(status) << "\r\n"
           << "Content-Type: " << contentType << "\r\n"
           << "Content-Length: " << body.size() << "\r\n"
           << "Access-Control-Allow-Origin: *\r\n"
           << "Access-Control-Allow-Methods: *\r\n"
           << "Access-Control-Allow-Headers: *\r\n"
           << "Connection: close\r\n\r\n"
           << body;
  return sendAll(fd, response.str());
}

bool parseRequest(const std::string &raw, HttpRequest &request) {
  const size_t headerEnd = raw.find("\r\n\r\n");
  if (headerEnd == std::string::npos) return false;

  std::istringstream stream(raw.substr(0, headerEnd));
  std::string requestLine;
  if (!std::getline(stream, requestLine)) return false;
  requestLine = trim(requestLine);

  std::istringstream requestLineStream(requestLine);
  if (!(requestLineStream >> request.method >> request.path)) return false;
  const size_t query = request.path.find('?');
  if (query != std::string::npos) request.path.erase(query);

  std::string line;
  while (std::getline(stream, line)) {
    const size_t separator = line.find(':');
    if (separator == std::string::npos) continue;
    request.headers[lower(trim(line.substr(0, separator)))] = trim(line.substr(separator + 1));
  }

  request.body = raw.substr(headerEnd + 4);
  return true;
}

size_t contentLengthFrom(const HttpRequest &request) {
  const auto it = request.headers.find("content-length");
  if (it == request.headers.end()) return 0;
  return static_cast<size_t>(std::strtoull(it->second.c_str(), nullptr, 10));
}

std::string readRequest(int fd) {
  std::string raw;
  char buffer[2048];
  size_t headerEnd = std::string::npos;
  size_t expectedLength = 0;

  while (raw.size() < MAX_HTTP_REQUEST_BYTES) {
    const ssize_t received = recv(fd, buffer, sizeof(buffer), 0);
    if (received <= 0) break;
    raw.append(buffer, static_cast<size_t>(received));

    if (headerEnd == std::string::npos) {
      headerEnd = raw.find("\r\n\r\n");
      if (headerEnd != std::string::npos) {
        HttpRequest parsed;
        if (parseRequest(raw, parsed)) expectedLength = headerEnd + 4 + contentLengthFrom(parsed);
      }
    }
    if (headerEnd != std::string::npos && raw.size() >= expectedLength) break;
  }
  return raw;
}

std::filesystem::path routeToAsset(const std::filesystem::path &webRoot, const std::string &path) {
  std::string asset = path;
  if (asset == "/") asset = "/index.htm";
  else if (asset == "/settings") asset = "/settings.htm";
  else if (asset == "/settings/wifi") asset = "/settings_wifi.htm";
  else if (asset == "/settings/leds") asset = "/settings_leds.htm";
  else if (asset == "/settings/pins") asset = "/settings_pininfo.htm";
  else if (asset == "/settings/2D") asset = "/settings_2D.htm";
  else if (asset == "/settings/ui") asset = "/settings_ui.htm";
  else if (asset == "/settings/dmx") asset = "/settings_dmx.htm";
  else if (asset == "/settings/sync") asset = "/settings_sync.htm";
  else if (asset == "/settings/time") asset = "/settings_time.htm";
  else if (asset == "/settings/um") asset = "/settings_um.htm";
  else if (asset == "/settings/sec") asset = "/settings_sec.htm";
  else if (asset == "/welcome") asset = "/welcome.htm";
  else if (asset == "/edit") asset = "/edit.htm";
  else if (asset == "/liveview") asset = "/liveview.htm";
  else if (asset == "/liveview2D") asset = "/liveviewws2D.htm";
  else if (asset == "/style.css") asset = "/style.css";

  if (asset.find("..") != std::string::npos) return {};
  if (!asset.empty() && asset[0] == '/') asset.erase(0, 1);
  return webRoot / asset;
}

std::string readFile(const std::filesystem::path &path) {
  std::ifstream file(path, std::ios::binary);
  if (!file) return "";
  std::ostringstream contents;
  contents << file.rdbuf();
  return contents.str();
}

std::string settingsCompatibilityJs() {
  return "/* native settings compatibility */\n"
         "function GetV(){}\n"
         "window.d=window.d||{};\n"
         "window.d.Sf={};\n";
}

bool bodyBool(const std::string &body, const std::string &key, bool &value) {
  const std::string marker = "\"" + key + "\"";
  const size_t keyPos = body.find(marker);
  if (keyPos == std::string::npos) return false;
  const size_t colon = body.find(':', keyPos + marker.size());
  if (colon == std::string::npos) return false;
  const std::string remaining = body.substr(colon + 1);
  const size_t first = remaining.find_first_not_of(" \t\r\n");
  if (first != std::string::npos && remaining.compare(first, 4, "true") == 0) {
    value = true;
    return true;
  }
  if (first != std::string::npos && remaining.compare(first, 5, "false") == 0) {
    value = false;
    return true;
  }
  return false;
}

bool bodyInt(const std::string &body, const std::string &key, int &value) {
  const std::string marker = "\"" + key + "\"";
  const size_t keyPos = body.find(marker);
  if (keyPos == std::string::npos) return false;
  const size_t colon = body.find(':', keyPos + marker.size());
  if (colon == std::string::npos) return false;
  char *end = nullptr;
  const long parsed = std::strtol(body.c_str() + colon + 1, &end, 10);
  if (end == body.c_str() + colon + 1) return false;
  value = static_cast<int>(parsed);
  return true;
}

bool sendWebSocketText(int fd, const std::string &payload) {
  std::string frame;
  frame.push_back(static_cast<char>(0x81));
  if (payload.size() < 126) {
    frame.push_back(static_cast<char>(payload.size()));
  } else {
    frame.push_back(static_cast<char>(126));
    frame.push_back(static_cast<char>((payload.size() >> 8) & 0xFF));
    frame.push_back(static_cast<char>(payload.size() & 0xFF));
  }
  frame += payload;
  return sendAll(fd, frame);
}

bool sendWebSocketBinary(int fd, const std::vector<uint8_t> &payload) {
  std::string frame;
  frame.push_back(static_cast<char>(0x82));
  if (payload.size() < 126) {
    frame.push_back(static_cast<char>(payload.size()));
  } else {
    frame.push_back(static_cast<char>(126));
    frame.push_back(static_cast<char>((payload.size() >> 8) & 0xFF));
    frame.push_back(static_cast<char>(payload.size() & 0xFF));
  }
  frame.append(reinterpret_cast<const char *>(payload.data()), payload.size());
  return sendAll(fd, frame);
}

bool readWebSocketFrame(int fd, uint8_t &opcode, std::string &payload) {
  uint8_t header[2] = {};
  if (recv(fd, header, sizeof(header), MSG_WAITALL) != 2) return false;
  opcode = header[0] & 0x0F;

  bool masked = (header[1] & 0x80) != 0;
  uint64_t length = header[1] & 0x7F;
  if (length == 126) {
    uint8_t extended[2] = {};
    if (recv(fd, extended, sizeof(extended), MSG_WAITALL) != 2) return false;
    length = (static_cast<uint64_t>(extended[0]) << 8) | extended[1];
  } else if (length == 127) {
    return false;
  }
  if (length > MAX_HTTP_REQUEST_BYTES) return false;

  uint8_t mask[4] = {};
  if (masked && recv(fd, mask, sizeof(mask), MSG_WAITALL) != 4) return false;

  payload.assign(static_cast<size_t>(length), '\0');
  if (length > 0 && recv(fd, payload.data(), payload.size(), MSG_WAITALL) != static_cast<ssize_t>(payload.size())) return false;
  if (masked) {
    for (size_t i = 0; i < payload.size(); i++) payload[i] = static_cast<char>(payload[i] ^ mask[i % 4]);
  }
  return true;
}

std::vector<uint8_t> liveViewPayload(const NativeRenderBuffer &renderBuffer) {
  std::vector<uint8_t> payload;
  payload.reserve(2 + renderBuffer.length() * 3);
  payload.push_back('L');
  payload.push_back(1);
  for (const NativeColor &color : renderBuffer.pixels()) {
    payload.push_back(static_cast<uint8_t>(std::min<int>(255, color.r + color.w)));
    payload.push_back(static_cast<uint8_t>(std::min<int>(255, color.g + color.w)));
    payload.push_back(static_cast<uint8_t>(std::min<int>(255, color.b + color.w)));
  }
  return payload;
}

void configureClientSocket(int client) {
#ifdef SO_NOSIGPIPE
  const int enabled = 1;
  setsockopt(client, SOL_SOCKET, SO_NOSIGPIPE, &enabled, sizeof(enabled));
#else
  (void)client;
#endif
}

} // namespace

NativeHttpServer::NativeHttpServer(const NativeHttpServerOptions &options) : _options(options), _fallbackRenderBuffer(30) {
  _fallbackCore.begin(_fallbackRenderBuffer.length(), millis());
}

NativeHttpServer::~NativeHttpServer() {
  stop();
}

NativeHttpServer::NativeHttpServer(NativeHttpServer &&other) noexcept {
  *this = std::move(other);
}

NativeHttpServer &NativeHttpServer::operator=(NativeHttpServer &&other) noexcept {
  if (this == &other) return *this;
  stop();
  _options = std::move(other._options);
  _fallbackRenderBuffer = std::move(other._fallbackRenderBuffer);
  _state = other._state;
  _running.store(other._running.load());
  _listenFd = other._listenFd;
  _localPort = other._localPort;
  _startMs = other._startMs;
  _fallbackCore.begin(_fallbackRenderBuffer.length(), millis());
  if (other._acceptThread.joinable()) _acceptThread = std::move(other._acceptThread);
  other._listenFd = -1;
  other._running.store(false);
  return *this;
}

bool NativeHttpServer::start() {
  if (_running.load()) return true;

  _listenFd = socket(AF_INET, SOCK_STREAM, 0);
  if (_listenFd < 0) return false;

  const int reuse = 1;
  setsockopt(_listenFd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));

  sockaddr_in address{};
  address.sin_family = AF_INET;
  address.sin_port = htons(_options.port);
  if (_options.host == "localhost") _options.host = "127.0.0.1";
  if (inet_pton(AF_INET, _options.host.c_str(), &address.sin_addr) != 1) {
    close(_listenFd);
    _listenFd = -1;
    return false;
  }

  if (bind(_listenFd, reinterpret_cast<sockaddr *>(&address), sizeof(address)) != 0) {
    close(_listenFd);
    _listenFd = -1;
    return false;
  }

  if (listen(_listenFd, 16) != 0) {
    close(_listenFd);
    _listenFd = -1;
    return false;
  }

  socklen_t length = sizeof(address);
  if (getsockname(_listenFd, reinterpret_cast<sockaddr *>(&address), &length) == 0) _localPort = ntohs(address.sin_port);
  else _localPort = _options.port;

  _startMs = millis();
  _running.store(true);
  _acceptThread = std::thread(&NativeHttpServer::acceptLoop, this);
  return true;
}

void NativeHttpServer::stop() {
  if (!_running.exchange(false) && _listenFd < 0) return;
  if (_listenFd >= 0) {
    shutdown(_listenFd, SHUT_RDWR);
    close(_listenFd);
    _listenFd = -1;
  }
  if (_acceptThread.joinable()) _acceptThread.join();
}

bool NativeHttpServer::running() const {
  return _running.load();
}

uint16_t NativeHttpServer::localPort() const {
  return _localPort;
}

const NativeLightState &NativeHttpServer::state() const {
  return _state;
}

void NativeHttpServer::acceptLoop() {
  while (_running.load()) {
    sockaddr_in remote{};
    socklen_t remoteLength = sizeof(remote);
    const int client = accept(_listenFd, reinterpret_cast<sockaddr *>(&remote), &remoteLength);
    if (client < 0) {
      if (_running.load()) std::this_thread::sleep_for(std::chrono::milliseconds(1));
      continue;
    }
    configureClientSocket(client);
    std::thread(&NativeHttpServer::handleClient, this, client).detach();
  }
}

void NativeHttpServer::handleClient(int clientFd) {
  const std::string raw = readRequest(clientFd);
  HttpRequest request;
  if (!parseRequest(raw, request)) {
    sendHttp(clientFd, 400, "text/plain; charset=utf-8", "Bad Request\n");
    close(clientFd);
    return;
  }

  if (request.path == "/ws" && lower(request.headers["upgrade"]) == "websocket") {
    handleWebSocket(clientFd, raw);
    close(clientFd);
    return;
  }

  core().tick(millis());

  if (request.method == "GET" && request.path == "/json/effects") {
    sendHttp(clientFd, 200, "application/json; charset=utf-8", core().jsonEffects());
  } else if (request.method == "GET" && request.path == "/json/fxdata") {
    sendHttp(clientFd, 200, "application/json; charset=utf-8", core().jsonFxData());
  } else if (request.method == "GET" && request.path == "/json/palettes") {
    sendHttp(clientFd, 200, "application/json; charset=utf-8", core().jsonPalettes());
  } else if (request.method == "GET" && request.path == "/json/palx") {
    sendHttp(clientFd, 200, "application/json; charset=utf-8", core().jsonPaletteData());
  } else if (request.method == "GET" && request.path == "/settings/s.js") {
    sendHttp(clientFd, 200, "application/javascript; charset=utf-8", settingsCompatibilityJs());
  } else if (request.method == "GET" && (request.path == "/json" || request.path == "/json/si")) {
    sendHttp(clientFd, 200, "application/json; charset=utf-8", jsonStateInfo());
  } else if (request.method == "GET" && request.path == "/json/state") {
    sendHttp(clientFd, 200, "application/json; charset=utf-8", jsonState());
  } else if (request.method == "GET" && request.path == "/json/info") {
    sendHttp(clientFd, 200, "application/json; charset=utf-8", jsonInfo());
  } else if (request.method == "GET" && request.path == "/presets.json") {
    sendHttp(clientFd, 200, "application/json; charset=utf-8", core().presetsJson());
  } else if (request.method == "POST" && (request.path == "/json" || request.path == "/json/state")) {
    applyJsonState(request.body);
    sendHttp(clientFd, 200, "application/json; charset=utf-8", "{\"success\":true}");
  } else if (request.method == "GET" && request.path == "/version") {
    sendHttp(clientFd, 200, "text/plain; charset=utf-8", _options.version);
  } else if (request.method == "GET" && request.path == "/uptime") {
    sendHttp(clientFd, 200, "text/plain; charset=utf-8", std::to_string(millis() - _startMs));
  } else if (request.method == "GET" && request.path == "/freeheap") {
    sendHttp(clientFd, 200, "text/plain; charset=utf-8", std::to_string(getFreeHeap()));
  } else if (request.path == "/update") {
    sendHttp(clientFd, 410, "text/plain; charset=utf-8", "Native WLED does not support firmware OTA updates.\n");
  } else if (request.path == "/upload") {
    sendHttp(clientFd, 501, "text/plain; charset=utf-8", "Native WLED upload endpoints are not implemented yet.\n");
  } else if (request.method == "GET") {
    const std::filesystem::path asset = routeToAsset(_options.webRoot, request.path);
    if (!asset.empty() && std::filesystem::is_regular_file(asset)) {
      sendHttp(clientFd, 200, contentTypeFor(asset), readFile(asset));
    } else {
      sendHttp(clientFd, 404, "text/plain; charset=utf-8", "Not Found\n");
    }
  } else {
    sendHttp(clientFd, 405, "text/plain; charset=utf-8", "Method Not Allowed\n");
  }
  close(clientFd);
}

void NativeHttpServer::handleWebSocket(int clientFd, const std::string &rawRequest) {
  HttpRequest request;
  if (!parseRequest(rawRequest, request)) return;
  const auto key = request.headers.find("sec-websocket-key");
  if (key == request.headers.end()) return;

  std::ostringstream response;
  response << "HTTP/1.1 101 Switching Protocols\r\n"
           << "Upgrade: websocket\r\n"
           << "Connection: Upgrade\r\n"
           << "Sec-WebSocket-Accept: " << websocketAccept(key->second) << "\r\n\r\n";
  if (!sendAll(clientFd, response.str())) return;
  if (!sendWebSocketText(clientFd, jsonStateInfo())) return;

  while (_running.load()) {
    uint8_t opcode = 0;
    std::string payload;
    if (!readWebSocketFrame(clientFd, opcode, payload)) break;
    if (opcode == 0x08) break;
    if (opcode != 0x01) continue;

    if (payload == "p") {
      if (!sendWebSocketText(clientFd, "pong")) break;
    } else if (payload.find("\"lv\"") != std::string::npos) {
      if (!sendWebSocketBinary(clientFd, liveViewPayload(renderBuffer()))) break;
    } else {
      applyJsonState(payload);
      if (payload.find("\"v\"") != std::string::npos) {
        if (!sendWebSocketText(clientFd, jsonStateInfo())) break;
      } else if (!sendWebSocketText(clientFd, "{\"success\":true}")) {
        break;
      }
    }
  }
}

std::string NativeHttpServer::jsonState() const {
  return core().jsonState(millis());
}

std::string NativeHttpServer::jsonInfo() const {
  return core().jsonInfo(_options.version, _options.nativeMac, renderBuffer(), millis());
}

std::string NativeHttpServer::jsonStateInfo() const {
  return core().jsonStateInfo(_options.version, _options.nativeMac, renderBuffer(), millis());
}

void NativeHttpServer::applyJsonState(const std::string &body) {
  core().applyJsonState(body, millis());
}

NativeRenderBuffer &NativeHttpServer::renderBuffer() {
  return _options.renderBuffer ? *_options.renderBuffer : _fallbackRenderBuffer;
}

const NativeRenderBuffer &NativeHttpServer::renderBuffer() const {
  return _options.renderBuffer ? *_options.renderBuffer : _fallbackRenderBuffer;
}

NativeWledCore &NativeHttpServer::core() {
  return _options.core ? *_options.core : _fallbackCore;
}

const NativeWledCore &NativeHttpServer::core() const {
  return _options.core ? *_options.core : _fallbackCore;
}
// AI: end
