#include "RenderBuffer.h"

#include <algorithm>

// AI: below section was generated by an AI
namespace {

uint8_t scaledChannelCurrent(uint8_t value, uint8_t channelMilliamps) {
  return static_cast<uint8_t>((static_cast<uint16_t>(value) * channelMilliamps + 254) / 255);
}

void appendRgb(std::vector<uint8_t> &encoded, const NativeColor &color, NativeColorOrder order) {
  switch (order) {
    case NativeColorOrder::GRB:
    case NativeColorOrder::GRBW:
      encoded.push_back(color.g);
      encoded.push_back(color.r);
      encoded.push_back(color.b);
      break;
    case NativeColorOrder::BRG:
      encoded.push_back(color.b);
      encoded.push_back(color.r);
      encoded.push_back(color.g);
      break;
    case NativeColorOrder::RGB:
    case NativeColorOrder::RGBW:
      encoded.push_back(color.r);
      encoded.push_back(color.g);
      encoded.push_back(color.b);
      break;
  }
}

bool hasWhiteChannel(NativeColorOrder order) {
  return order == NativeColorOrder::RGBW || order == NativeColorOrder::GRBW;
}

} // namespace

NativeRenderBuffer::NativeRenderBuffer(size_t length) : _pixels(length) {
}

bool NativeRenderBuffer::resize(size_t length) {
  _pixels.assign(length, NativeColor{});
  return _pixels.size() == length;
}

size_t NativeRenderBuffer::length() const {
  return _pixels.size();
}

void NativeRenderBuffer::clear() {
  std::fill(_pixels.begin(), _pixels.end(), NativeColor{});
}

void NativeRenderBuffer::setPixel(size_t index, const NativeColor &color) {
  if (index >= _pixels.size()) return;
  _pixels[index] = color;
}

NativeColor NativeRenderBuffer::pixel(size_t index) const {
  if (index >= _pixels.size()) return NativeColor{};
  return _pixels[index];
}

const std::vector<NativeColor> &NativeRenderBuffer::pixels() const {
  return _pixels;
}

std::vector<uint8_t> NativeRenderBuffer::encode(NativeColorOrder order) const {
  std::vector<uint8_t> encoded;
  encoded.reserve(_pixels.size() * (hasWhiteChannel(order) ? 4 : 3));
  for (const NativeColor &color : _pixels) {
    appendRgb(encoded, color, order);
    if (hasWhiteChannel(order)) encoded.push_back(color.w);
  }
  return encoded;
}

uint32_t NativeRenderBuffer::estimatedCurrentMilliamps() const {
  uint32_t milliamps = 0;
  for (const NativeColor &color : _pixels) {
    milliamps += scaledChannelCurrent(color.r, 20);
    milliamps += scaledChannelCurrent(color.g, 20);
    milliamps += scaledChannelCurrent(color.b, 20);
    milliamps += scaledChannelCurrent(color.w, 20);
  }
  return milliamps;
}

bool NativeRenderBuffer::hasVisiblePixels() const {
  for (const NativeColor &color : _pixels) {
    if (color.r != 0 || color.g != 0 || color.b != 0 || color.w != 0) return true;
  }
  return false;
}

bool NativeNullOutputBackend::begin(size_t length) {
  _length = length;
  _lastFrame.assign(length, NativeColor{});
  _frameCount = 0;
  return _lastFrame.size() == length;
}

bool NativeNullOutputBackend::show(const NativeRenderBuffer &buffer) {
  if (buffer.length() != _length) {
    if (!begin(buffer.length())) return false;
  }
  _lastFrame = buffer.pixels();
  _frameCount++;
  return true;
}

uint64_t NativeNullOutputBackend::frameCount() const {
  return _frameCount;
}

const std::vector<NativeColor> &NativeNullOutputBackend::lastFrame() const {
  return _lastFrame;
}
// AI: end
