#include "NativeWledCore.h"

#include "../../wled00/src/dependencies/json/ArduinoJson-v6.h"
#include "../arduino_compat/Arduino.h"

#undef max
#undef min

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <sstream>

// AI: below section was generated by an AI
namespace {

// Native effect names and behavior are a bring-up subset inspired by WLED's
// wled00/FX.cpp mode IDs and wled00/json.cpp state shape.
const std::vector<std::string> &effectNames() {
  static const std::vector<std::string> names = {
    "Solid", "Blink", "Breathe", "Wipe", "Wipe Random", "Random Colors", "Sweep", "Dynamic",
    "Colorloop", "Rainbow", "Scan", "Scan Dual", "Fade", "Theater", "Theater Rainbow", "Running",
    "Saw", "Twinkle", "Dissolve", "Dissolve Rnd", "Sparkle", "Sparkle Dark", "Sparkle+",
    "Strobe", "Strobe Rainbow", "Strobe Mega", "Blink Rainbow", "Android", "Chase",
    "Chase Random", "Chase Rainbow", "Chase Flash", "Chase Flash Rnd", "Rainbow Runner",
    "Colorful", "Traffic Light", "Sweep Random", "Chase 2", "Aurora", "Stream", "Scanner",
    "Lighthouse", "Fireworks", "Rain", "Tetrix", "Fire Flicker", "Gradient", "Loading",
    "Rolling Balls", "Fairy", "Two Dots", "Fairytwinkle", "Running Dual", "Image",
    "Chase 3", "Tri Wipe", "Tri Fade", "Lightning", "ICU", "Multi Comet", "Scanner Dual",
    "Stream 2", "Oscillate", "Pride 2015", "Juggle", "Palette", "Fire 2012", "Colorwaves",
    "Bpm", "Fill Noise", "Noise 1", "Noise 2", "Noise 3", "Noise 4", "Colortwinkles",
    "Lake", "Meteor", "Copy Segment", "Railway", "Ripple", "Twinklefox", "Twinklecat",
    "Halloween Eyes", "Solid Pattern", "Solid Pattern Tri", "Spots", "Spots Fade", "Glitter",
    "Candle", "Fireworks Starburst", "Fireworks 1D", "Bouncing Balls", "Sinelon",
    "Sinelon Dual", "Sinelon Rainbow", "Drip", "Plasma", "Percent", "Ripple Rainbow",
    "Heartbeat", "Pacifica", "Candle Multi", "Sunrise", "Phased", "Phased Noise", "Twinkleup",
    "Noise Pal", "Sine", "Flow", "Chunchun", "Dancing Shadows", "Washing Machine", "Blends",
    "TV Simulator", "Dynamic Smooth", "PacMan", "Slow Transition", "Pixels", "Pixelwave",
    "Juggles", "Matripix", "Gravimeter", "Plasmoid", "Puddles", "Midnoise", "Noisemeter",
    "Freqwave", "Freqmatrix", "Waterfall", "Freqpixels", "Noisefire", "Puddlepeak",
    "Noisemove", "Perlin Move", "Ripple Peak", "Freqmap", "Gravcenter", "Gravcentric",
    "Gravfreq", "DJ Light", "Blurz", "Flow Stripe", "Wavesins", "Rocktaves", "Shimmer",
    "Rotozoomer", "Spaceships", "Crazy Bees", "Ghost Rider", "Blobs", "Scrolling Text",
    "Drift Rose", "Distortion Waves", "GEQ", "Noise2D", "Firenoise", "Squared Swirl", "DNA",
    "Matrix", "Metaballs", "Funky Plank", "Pulser", "Drift", "Waverly", "Sun Radiation",
    "Colored Bursts", "Julia", "Game Of Life", "Tartan", "Polar Lights", "Swirl", "Lissajous",
    "Frizzles", "Plasma Ball", "Hiphotic", "Sindots", "DNA Spiral", "Black Hole", "Soap",
    "Octopus", "Waving Cell", "Akemi"
  };
  return names;
}

const std::vector<std::string> &paletteNames() {
  static const std::vector<std::string> names = {
    "Default", "* Random Cycle", "Primary Color", "Based on Primary", "Set Colors", "Based on Set",
    "Party", "Cloud", "Lava", "Ocean", "Forest", "Rainbow", "Rainbow Bands", "Sunset",
    "Rivendell", "Breeze", "Red & Blue", "Yellowout", "Analogous", "Splash"
  };
  return names;
}

std::string jsonEscape(const std::string &value) {
  std::ostringstream out;
  for (char c : value) {
    switch (c) {
      case '\\': out << "\\\\"; break;
      case '"': out << "\\\""; break;
      case '\n': out << "\\n"; break;
      case '\r': out << "\\r"; break;
      case '\t': out << "\\t"; break;
      default: out << c; break;
    }
  }
  return out.str();
}

std::string jsonStringArray(const std::vector<std::string> &values) {
  std::ostringstream json;
  json << "[";
  for (size_t i = 0; i < values.size(); i++) {
    if (i > 0) json << ",";
    json << "\"" << jsonEscape(values[i]) << "\"";
  }
  json << "]";
  return json.str();
}

uint8_t clampByte(int value) {
  if (value < 0) return 0;
  if (value > 255) return 255;
  return static_cast<uint8_t>(value);
}

NativeColor colorFromJson(JsonArray array, NativeColor fallback) {
  if (array.isNull() || array.size() < 3) return fallback;
  fallback.r = clampByte(array[0] | fallback.r);
  fallback.g = clampByte(array[1] | fallback.g);
  fallback.b = clampByte(array[2] | fallback.b);
  if (array.size() > 3) fallback.w = clampByte(array[3] | fallback.w);
  return fallback;
}

void addColorJson(std::ostringstream &json, const NativeColor &color) {
  json << "[" << static_cast<int>(color.r)
       << "," << static_cast<int>(color.g)
       << "," << static_cast<int>(color.b)
       << "," << static_cast<int>(color.w) << "]";
}

NativeColor scaleColor(NativeColor color, uint8_t amount) {
  color.r = static_cast<uint8_t>((static_cast<uint16_t>(color.r) * amount) / 255);
  color.g = static_cast<uint8_t>((static_cast<uint16_t>(color.g) * amount) / 255);
  color.b = static_cast<uint8_t>((static_cast<uint16_t>(color.b) * amount) / 255);
  color.w = static_cast<uint8_t>((static_cast<uint16_t>(color.w) * amount) / 255);
  return color;
}

NativeColor blend(NativeColor a, NativeColor b, uint8_t amount) {
  const uint16_t inverse = 255 - amount;
  return NativeColor{
    static_cast<uint8_t>((a.r * inverse + b.r * amount) / 255),
    static_cast<uint8_t>((a.g * inverse + b.g * amount) / 255),
    static_cast<uint8_t>((a.b * inverse + b.b * amount) / 255),
    static_cast<uint8_t>((a.w * inverse + b.w * amount) / 255),
    0
  };
}

NativeColor hsv(uint16_t hue, uint8_t sat, uint8_t val) {
  const uint8_t region = (hue / 43) % 6;
  const uint8_t remainder = static_cast<uint8_t>((hue - (region * 43)) * 6);
  const uint8_t p = static_cast<uint8_t>((static_cast<uint16_t>(val) * (255 - sat)) >> 8);
  const uint8_t q = static_cast<uint8_t>((static_cast<uint16_t>(val) * (255 - ((static_cast<uint16_t>(sat) * remainder) >> 8))) >> 8);
  const uint8_t t = static_cast<uint8_t>((static_cast<uint16_t>(val) * (255 - ((static_cast<uint16_t>(sat) * (255 - remainder)) >> 8))) >> 8);

  switch (region) {
    case 0: return NativeColor{val, t, p, 0, 0};
    case 1: return NativeColor{q, val, p, 0, 0};
    case 2: return NativeColor{p, val, t, 0, 0};
    case 3: return NativeColor{p, q, val, 0, 0};
    case 4: return NativeColor{t, p, val, 0, 0};
    default: return NativeColor{val, p, q, 0, 0};
  }
}

NativeColor paletteColor(uint8_t palette, uint16_t index, const NativeSegmentState &segment) {
  switch (palette) {
    case 2: return segment.colors[0];
    case 3: return blend(segment.colors[0], NativeColor{255, 255, 255, 0, 0}, index & 0xFF);
    case 4: return blend(segment.colors[0], segment.colors[1], index & 0xFF);
    case 8: return blend(NativeColor{255, 80, 0, 0, 0}, NativeColor{120, 0, 0, 0, 0}, index & 0xFF);
    case 9: return blend(NativeColor{0, 32, 180, 0, 0}, NativeColor{0, 220, 255, 0, 0}, index & 0xFF);
    case 10: return blend(NativeColor{0, 120, 0, 0, 0}, NativeColor{160, 255, 80, 0, 0}, index & 0xFF);
    case 11:
    case 12: return hsv(index, 255, 255);
    case 16: return (index & 0x80) ? NativeColor{0, 0, 255, 0, 0} : NativeColor{255, 0, 0, 0, 0};
    default: return blend(segment.colors[0], hsv(index, 255, 255), palette == 0 ? 0 : 96);
  }
}

uint32_t stableNoise(uint32_t value) {
  value ^= value >> 16;
  value *= 0x7feb352dU;
  value ^= value >> 15;
  value *= 0x846ca68bU;
  value ^= value >> 16;
  return value;
}

void renderSegmentEffect(const NativeCoreState &state, const NativeSegmentState &segment, NativeRenderBuffer &buffer, uint64_t nowMs) {
  if (!state.on || !segment.on || state.bri == 0 || segment.bri == 0) return;

  const uint16_t start = std::min<uint16_t>(segment.start, buffer.length());
  const uint16_t stop = std::min<uint16_t>(segment.stop, buffer.length());
  if (stop <= start) return;

  const uint16_t length = stop - start;
  const uint16_t phase = static_cast<uint16_t>((nowMs / std::max<uint8_t>(1, 256 - segment.sx)) & 0xFFFF);
  const uint8_t totalBrightness = static_cast<uint8_t>((static_cast<uint16_t>(state.bri) * segment.bri) / 255);

  for (uint16_t offset = 0; offset < length; offset++) {
    NativeColor color = segment.colors[0];
    const uint16_t wheel = static_cast<uint16_t>((offset * 256U / std::max<uint16_t>(1, length)) + phase);

    switch (segment.fx) {
      case 0: // Solid
        color = segment.colors[0];
        break;
      case 1: // Blink
      case 23: // Strobe
        color = ((nowMs / std::max<uint16_t>(80, 600 - segment.sx * 2)) & 1) ? segment.colors[0] : segment.colors[1];
        break;
      case 2: // Breathe
      case 12: { // Fade
        const double radians = static_cast<double>(phase % 1024) * 6.283185307179586 / 1024.0;
        color = scaleColor(segment.colors[0], static_cast<uint8_t>(24 + (std::sin(radians) + 1.0) * 115.0));
        break;
      }
      case 8: // Colorloop
      case 9: // Rainbow
      case 14:
      case 30:
        color = hsv(wheel, 255, 255);
        break;
      case 13: // Theater
      case 28: // Chase
        color = (((offset + phase / 8) % 6) < 2) ? segment.colors[0] : segment.colors[1];
        break;
      case 20: // Sparkle
      case 87:
      case 103: {
        const uint32_t noise = stableNoise(static_cast<uint32_t>(offset) + static_cast<uint32_t>(nowMs / 80));
        color = (noise % 100) < std::max<uint8_t>(4, segment.ix / 8) ? NativeColor{255, 255, 255, 0, 0} : segment.colors[0];
        break;
      }
      case 46: // Gradient
      case 65: // Palette
        color = paletteColor(segment.pal, wheel, segment);
        break;
      case 76: { // Meteor
        const uint16_t head = static_cast<uint16_t>((phase / 2) % length);
        const uint16_t distance = (offset > head) ? offset - head : head - offset;
        color = scaleColor(segment.colors[0], distance < 8 ? static_cast<uint8_t>(255 - distance * 28) : 0);
        break;
      }
      case 92:
      case 93:
      case 94: { // Sinelon family
        const double radians = static_cast<double>(phase % 1024) * 6.283185307179586 / 1024.0;
        const uint16_t center = static_cast<uint16_t>((std::sin(radians) + 1.0) * 0.5 * (length - 1));
        const uint16_t distance = (offset > center) ? offset - center : center - offset;
        color = distance < 6 ? scaleColor(paletteColor(segment.pal, wheel, segment), static_cast<uint8_t>(255 - distance * 38)) : NativeColor{};
        break;
      }
      default:
        color = paletteColor(segment.pal, static_cast<uint16_t>(wheel + segment.fx * 19), segment);
        if (((segment.fx >= 112 && segment.fx <= 143) || segment.fx >= 146) && segment.ix == 0) {
          color = scaleColor(color, 160); // Audioreactive fallback when no microphone data exists.
        }
        break;
    }

    buffer.setPixel(start + offset, scaleColor(color, totalBrightness));
  }
}

} // namespace

NativeWledCore::NativeWledCore(std::filesystem::path configRoot) : _configRoot(std::move(configRoot)) {
}

void NativeWledCore::begin(size_t ledCount, uint64_t nowMs) {
  std::lock_guard<std::mutex> lock(_mutex);
  _startedMs = nowMs;
  ensureDefaults(ledCount);
  ensurePresetsFile();
}

void NativeWledCore::ensureDefaults(size_t ledCount) {
  if (_state.segments.empty()) {
    NativeSegmentState segment;
    segment.stop = static_cast<uint16_t>(std::min<size_t>(ledCount, UINT16_MAX));
    _state.segments.push_back(segment);
  } else {
    _state.segments[0].start = 0;
    _state.segments[0].stop = static_cast<uint16_t>(std::min<size_t>(ledCount, UINT16_MAX));
  }
}

void NativeWledCore::ensurePresetsFile() const {
  if (_configRoot.empty()) return;
  std::error_code error;
  std::filesystem::create_directories(_configRoot, error);
  const std::filesystem::path presets = _configRoot / "presets.json";
  if (std::filesystem::exists(presets, error)) return;
  std::ofstream file(presets);
  file << "{\"0\":{}}\n";
}

void NativeWledCore::tick(uint64_t nowMs) {
  std::lock_guard<std::mutex> lock(_mutex);
  if (_state.nightlight.active && _state.nightlight.durationMinutes > 0) {
    const uint64_t durationMs = static_cast<uint64_t>(_state.nightlight.durationMinutes) * 60000ULL;
    if (nowMs - _state.nightlight.startedMs >= durationMs) {
      _state.bri = _state.nightlight.targetBri;
      if (_state.bri == 0) _state.on = false;
      _state.nightlight.active = false;
    }
  }

  if (_playlist.active && !_playlist.entries.empty()) {
    const PlaylistEntry &entry = _playlist.entries[_playlist.index];
    if (nowMs - _playlist.entryStartedMs >= entry.durationMs) advancePlaylistLocked(nowMs);
  }
}

void NativeWledCore::render(NativeRenderBuffer &buffer, uint64_t nowMs) {
  std::lock_guard<std::mutex> lock(_mutex);
  buffer.clear();
  NativeCoreState effective = _state;
  effective.bri = effectiveBrightness(nowMs);
  for (const NativeSegmentState &segment : effective.segments) renderSegmentEffect(effective, segment, buffer, nowMs);
}

void NativeWledCore::applyJsonState(const std::string &json, uint64_t nowMs) {
  std::lock_guard<std::mutex> lock(_mutex);
  applyJsonStateLocked(json, nowMs, false);
}

void NativeWledCore::applyJsonStateLocked(const std::string &json, uint64_t nowMs, bool fromPreset) {
  DynamicJsonDocument doc(12288);
  if (deserializeJson(doc, json) != DeserializationError::Ok) return;
  JsonObject root = doc.as<JsonObject>();

  if (!fromPreset && root["psave"].is<int>()) {
    savePreset(static_cast<uint8_t>(root["psave"] | 0));
  }

  if (!fromPreset && root["ps"].is<int>()) {
    _playlist.active = false;
    applyPresetJson(static_cast<uint8_t>(root["ps"] | 0), presetObjectJson(static_cast<uint8_t>(root["ps"] | 0)), nowMs);
    return;
  }

  if (root["on"].is<bool>()) _state.on = root["on"].as<bool>();
  if (root["bri"].is<int>()) _state.bri = clampByte(root["bri"].as<int>());
  if (root["transition"].is<int>()) _state.transitionMs = static_cast<uint16_t>(std::max(0, root["transition"].as<int>()) * 100);
  if (root["np"].as<bool>()) advancePlaylistLocked(nowMs);

  JsonObject nl = root["nl"];
  if (!nl.isNull()) {
    if (nl["dur"].is<int>()) _state.nightlight.durationMinutes = static_cast<uint16_t>(std::max(0, nl["dur"].as<int>()));
    if (nl["mode"].is<int>()) _state.nightlight.mode = clampByte(nl["mode"].as<int>());
    if (nl["tbri"].is<int>()) _state.nightlight.targetBri = clampByte(nl["tbri"].as<int>());
    if (nl["on"].is<bool>()) {
      _state.nightlight.active = nl["on"].as<bool>();
      if (_state.nightlight.active) _state.nightlight.startedMs = nowMs;
    }
  }

  JsonArray segments = root["seg"];
  if (!segments.isNull()) {
    for (JsonObject incoming : segments) {
      const size_t index = incoming["id"] | 0;
      if (index >= _state.segments.size()) _state.segments.resize(index + 1);
      NativeSegmentState &segment = _state.segments[index];
      segment.id = static_cast<uint16_t>(index);
      if (incoming["start"].is<int>()) segment.start = static_cast<uint16_t>(std::max(0, incoming["start"].as<int>()));
      if (incoming["stop"].is<int>()) segment.stop = static_cast<uint16_t>(std::max(0, incoming["stop"].as<int>()));
      if (incoming["len"].is<int>()) segment.stop = static_cast<uint16_t>(segment.start + std::max(0, incoming["len"].as<int>()));
      if (incoming["on"].is<bool>()) segment.on = incoming["on"].as<bool>();
      if (incoming["bri"].is<int>()) segment.bri = clampByte(incoming["bri"].as<int>());
      if (incoming["fx"].is<int>()) segment.fx = clampByte(incoming["fx"].as<int>());
      if (incoming["sx"].is<int>()) segment.sx = clampByte(incoming["sx"].as<int>());
      if (incoming["ix"].is<int>()) segment.ix = clampByte(incoming["ix"].as<int>());
      if (incoming["pal"].is<int>()) segment.pal = clampByte(incoming["pal"].as<int>());
      JsonArray colors = incoming["col"];
      for (size_t i = 0; i < 3 && !colors.isNull() && i < colors.size(); i++) {
        segment.colors[i] = colorFromJson(colors[i], segment.colors[i]);
      }
    }
  }

  if (!root["playlist"].isNull()) loadPlaylistFromJsonLocked(0, json, nowMs);
  if (fromPreset) _state.currentPreset = root["n"].isNull() ? _state.currentPreset : _state.currentPreset;
}

std::string NativeWledCore::presetObjectJson(uint8_t presetId) const {
  if (_configRoot.empty() || presetId == 0) return "";
  std::ifstream file(_configRoot / "presets.json");
  if (!file) return "";
  std::ostringstream contents;
  contents << file.rdbuf();

  DynamicJsonDocument doc(65536);
  if (deserializeJson(doc, contents.str()) != DeserializationError::Ok) return "";
  JsonVariant preset = doc[String(presetId).c_str()];
  if (preset.isNull()) return "";
  std::string json;
  serializeJson(preset, json);
  return json;
}

bool NativeWledCore::applyPresetJson(uint8_t presetId, const std::string &json, uint64_t nowMs) {
  if (json.empty()) return false;
  _state.currentPreset = presetId;
  applyJsonStateLocked(json, nowMs, true);
  return true;
}

bool NativeWledCore::applyPreset(uint8_t presetId, uint64_t nowMs) {
  std::lock_guard<std::mutex> lock(_mutex);
  _playlist.active = false;
  return applyPresetJson(presetId, presetObjectJson(presetId), nowMs);
}

bool NativeWledCore::savePreset(uint8_t presetId) {
  if (_configRoot.empty() || presetId == 0 || presetId > 250) return false;
  ensurePresetsFile();

  std::ifstream in(_configRoot / "presets.json");
  std::ostringstream contents;
  contents << in.rdbuf();

  DynamicJsonDocument doc(65536);
  if (deserializeJson(doc, contents.str()) != DeserializationError::Ok) doc.to<JsonObject>();
  JsonObject root = doc.as<JsonObject>();
  JsonObject preset = root.createNestedObject(String(presetId).c_str());
  preset["n"] = "Native preset";
  preset["on"] = _state.on;
  preset["bri"] = _state.bri;
  JsonArray segs = preset.createNestedArray("seg");
  for (const NativeSegmentState &segment : _state.segments) {
    JsonObject s = segs.createNestedObject();
    s["id"] = segment.id;
    s["start"] = segment.start;
    s["stop"] = segment.stop;
    s["fx"] = segment.fx;
    s["sx"] = segment.sx;
    s["ix"] = segment.ix;
    s["pal"] = segment.pal;
    JsonArray colors = s.createNestedArray("col");
    for (const NativeColor &color : segment.colors) {
      JsonArray c = colors.createNestedArray();
      c.add(color.r);
      c.add(color.g);
      c.add(color.b);
      c.add(color.w);
    }
  }

  std::ofstream out(_configRoot / "presets.json");
  if (!out) return false;
  serializeJson(doc, out);
  out << "\n";
  return true;
}

bool NativeWledCore::loadPlaylistFromJsonLocked(uint8_t presetId, const std::string &json, uint64_t nowMs) {
  DynamicJsonDocument doc(16384);
  if (deserializeJson(doc, json) != DeserializationError::Ok) return false;
  JsonObject playlist = doc["playlist"];
  if (playlist.isNull()) return false;

  JsonArray presets = playlist["ps"];
  if (presets.isNull() || presets.size() == 0) return false;

  PlaylistState next;
  next.active = true;
  next.presetId = presetId;
  next.repeatRemaining = static_cast<uint16_t>(std::max(0, playlist["repeat"] | 1));
  next.endPreset = playlist["end"] | 0;
  next.shuffle = playlist["r"] | false;
  next.entryStartedMs = nowMs;

  JsonArray durations = playlist["dur"];
  JsonArray transitions = playlist["transition"];
  for (size_t i = 0; i < presets.size() && i < 100; i++) {
    PlaylistEntry entry;
    entry.preset = presets[i] | 0;
    const int dur = durations.isNull() ? (playlist["dur"] | 100) : (durations[i] | 100);
    entry.durationMs = static_cast<uint32_t>(std::max(0, dur)) * 100UL;
    const int transition = transitions.isNull() ? (playlist["transition"] | 7) : (transitions[i] | 7);
    entry.transitionMs = static_cast<uint16_t>(std::max(0, transition) * 100);
    next.entries.push_back(entry);
  }

  _playlist = next;
  _state.currentPlaylist = presetId > 0 ? presetId : 0;
  applyPlaylistEntryLocked(nowMs);
  return true;
}

void NativeWledCore::applyPlaylistEntryLocked(uint64_t nowMs) {
  if (!_playlist.active || _playlist.entries.empty()) return;
  const PlaylistEntry &entry = _playlist.entries[_playlist.index];
  _state.transitionMs = entry.transitionMs;
  const std::string preset = presetObjectJson(entry.preset);
  if (!preset.empty()) applyPresetJson(entry.preset, preset, nowMs);
  _playlist.entryStartedMs = nowMs;
}

void NativeWledCore::advancePlaylist(uint64_t nowMs) {
  std::lock_guard<std::mutex> lock(_mutex);
  advancePlaylistLocked(nowMs);
}

void NativeWledCore::advancePlaylistLocked(uint64_t nowMs) {
  if (!_playlist.active || _playlist.entries.empty()) return;
  _playlist.index++;
  if (_playlist.index >= _playlist.entries.size()) {
    _playlist.index = 0;
    if (_playlist.repeatRemaining == 1) {
      const uint8_t endPreset = _playlist.endPreset;
      _playlist = PlaylistState{};
      _state.currentPlaylist = -1;
      if (endPreset > 0 && endPreset < 251) applyPresetJson(endPreset, presetObjectJson(endPreset), nowMs);
      return;
    }
    if (_playlist.repeatRemaining > 1) _playlist.repeatRemaining--;
    if (_playlist.shuffle && _playlist.entries.size() > 1) std::rotate(_playlist.entries.begin(), _playlist.entries.begin() + 1, _playlist.entries.end());
  }
  applyPlaylistEntryLocked(nowMs);
}

uint8_t NativeWledCore::effectiveBrightness(uint64_t nowMs) const {
  if (!_state.nightlight.active || _state.nightlight.durationMinutes == 0) return _state.bri;

  const uint64_t durationMs = static_cast<uint64_t>(_state.nightlight.durationMinutes) * 60000ULL;
  const uint64_t elapsed = std::min<uint64_t>(durationMs, nowMs - _state.nightlight.startedMs);
  const int start = _state.bri;
  const int target = _state.nightlight.targetBri;
  return clampByte(start + static_cast<int>((static_cast<int64_t>(target - start) * static_cast<int64_t>(elapsed)) / static_cast<int64_t>(durationMs)));
}

std::string NativeWledCore::jsonState(uint64_t nowMs) const {
  std::lock_guard<std::mutex> lock(_mutex);
  std::ostringstream json;
  json << "{\"on\":" << (_state.on ? "true" : "false")
       << ",\"bri\":" << static_cast<int>(effectiveBrightness(nowMs))
       << ",\"transition\":" << (_state.transitionMs / 100)
       << ",\"ps\":" << static_cast<int>(_state.currentPreset)
       << ",\"pl\":" << _state.currentPlaylist
       << ",\"nl\":{\"on\":" << (_state.nightlight.active ? "true" : "false")
       << ",\"dur\":" << _state.nightlight.durationMinutes
       << ",\"mode\":" << static_cast<int>(_state.nightlight.mode)
       << ",\"tbri\":" << static_cast<int>(_state.nightlight.targetBri)
       << ",\"rem\":";
  if (_state.nightlight.active) {
    const uint64_t durationMs = static_cast<uint64_t>(_state.nightlight.durationMinutes) * 60000ULL;
    const uint64_t elapsed = std::min<uint64_t>(durationMs, nowMs - _state.nightlight.startedMs);
    json << static_cast<int>((durationMs - elapsed) / 1000);
  } else {
    json << -1;
  }
  json << "},\"seg\":[";
  for (size_t i = 0; i < _state.segments.size(); i++) {
    const NativeSegmentState &segment = _state.segments[i];
    if (i > 0) json << ",";
    json << "{\"id\":" << segment.id
         << ",\"start\":" << segment.start
         << ",\"stop\":" << segment.stop
         << ",\"len\":" << (segment.stop > segment.start ? segment.stop - segment.start : 0)
         << ",\"on\":" << (segment.on ? "true" : "false")
         << ",\"bri\":" << static_cast<int>(segment.bri)
         << ",\"fx\":" << static_cast<int>(segment.fx)
         << ",\"sx\":" << static_cast<int>(segment.sx)
         << ",\"ix\":" << static_cast<int>(segment.ix)
         << ",\"pal\":" << static_cast<int>(segment.pal)
         << ",\"col\":[";
    for (size_t c = 0; c < 3; c++) {
      if (c > 0) json << ",";
      addColorJson(json, segment.colors[c]);
    }
    json << "]}";
  }
  json << "]}";
  return json.str();
}

std::string NativeWledCore::jsonInfo(const std::string &version, const std::string &nativeMac, const NativeRenderBuffer &buffer, uint64_t nowMs) const {
  std::lock_guard<std::mutex> lock(_mutex);
  std::ostringstream json;
  json << "{\"ver\":\"" << jsonEscape(version)
       << "\",\"vid\":1700000"
       << ",\"leds\":{\"count\":" << buffer.length()
       << ",\"rgbw\":true,\"wv\":true,\"pwr\":" << buffer.estimatedCurrentMilliamps() << "}"
       << ",\"fxcount\":" << effectNames().size()
       << ",\"palcount\":" << paletteNames().size()
       << ",\"cpalcount\":0,\"umpalcount\":0,\"cpalmax\":0"
       << ",\"name\":\"WLED Native\""
       << ",\"mac\":\"" << jsonEscape(nativeMac) << "\""
       << ",\"freeheap\":" << getFreeHeap()
       << ",\"uptime\":" << ((nowMs - _startedMs) / 1000)
       << ",\"time\":\"" << (nowMs / 1000) << "\""
       << "}";
  return json.str();
}

std::string NativeWledCore::jsonStateInfo(const std::string &version, const std::string &nativeMac, const NativeRenderBuffer &buffer, uint64_t nowMs) const {
  return "{\"state\":" + jsonState(nowMs) + ",\"info\":" + jsonInfo(version, nativeMac, buffer, nowMs) + "}";
}

std::string NativeWledCore::jsonEffects() const {
  return jsonStringArray(effectNames());
}

std::string NativeWledCore::jsonFxData() const {
  std::vector<std::string> data;
  data.reserve(effectNames().size());
  for (const std::string &name : effectNames()) data.push_back(name + "@!,!;!,!,!;!;01");
  return jsonStringArray(data);
}

std::string NativeWledCore::jsonPalettes() const {
  return jsonStringArray(paletteNames());
}

std::string NativeWledCore::jsonPaletteData() const {
  return "{\"m\":0,\"p\":{\"0\":[0,255,160,0,255,255,255],\"11\":[0,255,0,0,85,0,255,0,170,0,0,255],\"16\":[0,255,0,0,128,0,0,255]}}";
}

std::string NativeWledCore::presetsJson() const {
  if (_configRoot.empty()) return "{\"0\":{}}";
  ensurePresetsFile();
  std::ifstream file(_configRoot / "presets.json");
  if (!file) return "{\"0\":{}}";
  std::ostringstream contents;
  contents << file.rdbuf();
  return contents.str();
}

NativeCoreSnapshot NativeWledCore::snapshot(uint64_t nowMs) const {
  std::lock_guard<std::mutex> lock(_mutex);
  NativeCoreSnapshot snapshot;
  snapshot.state = _state;
  snapshot.effects = effectNames();
  snapshot.effectData.reserve(effectNames().size());
  for (const std::string &name : effectNames()) snapshot.effectData.push_back(name + "@!,!;!,!,!;!;01");
  snapshot.palettes = paletteNames();
  snapshot.uptimeSeconds = (nowMs - _startedMs) / 1000;
  return snapshot;
}

const std::filesystem::path &NativeWledCore::configRoot() const {
  return _configRoot;
}
// AI: end
