#include <cstdlib>
#include <iostream>
#include <string>

#ifndef WLED_NATIVE_VERSION
#define WLED_NATIVE_VERSION "dev"
#endif

// AI: below section was generated by an AI
namespace {

struct CliOptions {
  std::string configDir;
  std::string host = "127.0.0.1";
  unsigned int port = 8080;
  std::string logLevel = "info";
  bool showHelp = false;
  bool showVersion = false;
};

void printHelp(std::ostream &out) {
  out << "WLED native runtime\n"
      << "\n"
      << "Usage: wled-native [options]\n"
      << "\n"
      << "Options:\n"
      << "  --help                 Show this help text and exit\n"
      << "  --version              Show the WLED version and exit\n"
      << "  --config-dir <path>    Placeholder for the native config root\n"
      << "  --host <address>       Placeholder bind address (default: 127.0.0.1)\n"
      << "  --port <port>          Placeholder HTTP port (default: 8080)\n"
      << "  --log-level <level>    Placeholder log level (default: info)\n";
}

void printVersion(std::ostream &out) {
  out << "WLED " << WLED_NATIVE_VERSION << " (wled-native)\n";
}

bool readValue(int argc, char **argv, int &index, const char *name, std::string &value, std::ostream &err) {
  if (index + 1 >= argc) {
    err << "Missing value for " << name << "\n";
    return false;
  }

  value = argv[++index];
  return true;
}

// Validates the placeholder HTTP port without using exception-throwing conversions.
bool parsePort(const std::string &value, unsigned int &port) {
  char *end = nullptr;
  const long parsed = std::strtol(value.c_str(), &end, 10);
  if (end == value.c_str() || *end != '\0' || parsed < 1 || parsed > 65535) return false;

  port = static_cast<unsigned int>(parsed);
  return true;
}

// Parses stable CLI placeholders before the native runtime and server are implemented.
bool parseArgs(int argc, char **argv, CliOptions &options, std::ostream &err) {
  for (int i = 1; i < argc; i++) {
    const std::string arg = argv[i];
    if (arg == "--help" || arg == "-h") {
      options.showHelp = true;
    } else if (arg == "--version") {
      options.showVersion = true;
    } else if (arg == "--config-dir") {
      if (!readValue(argc, argv, i, "--config-dir", options.configDir, err)) return false;
    } else if (arg == "--host") {
      if (!readValue(argc, argv, i, "--host", options.host, err)) return false;
    } else if (arg == "--port") {
      std::string value;
      if (!readValue(argc, argv, i, "--port", value, err)) return false;
      if (!parsePort(value, options.port)) {
        err << "Invalid value for --port: " << value << "\n";
        return false;
      }
    } else if (arg == "--log-level") {
      if (!readValue(argc, argv, i, "--log-level", options.logLevel, err)) return false;
    } else {
      err << "Unknown option: " << arg << "\n";
      return false;
    }
  }

  return true;
}

// Runs the current skeleton command and prints enough state for scripts to verify it.
int run(int argc, char **argv, std::ostream &out, std::ostream &err) {
  CliOptions options;
  if (!parseArgs(argc, argv, options, err)) {
    err << "Run 'wled-native --help' for usage.\n";
    return 64;
  }

  if (options.showHelp) {
    printHelp(out);
    return 0;
  }

  if (options.showVersion) {
    printVersion(out);
    return 0;
  }

  out << "WLED native runtime skeleton\n"
      << "Runtime services are not started yet.\n"
      << "host=" << options.host << "\n"
      << "port=" << options.port << "\n"
      << "logLevel=" << options.logLevel << "\n";
  if (!options.configDir.empty()) out << "configDir=" << options.configDir << "\n";

  return 0;
}

} // namespace

int main(int argc, char **argv) {
  return run(argc, argv, std::cout, std::cerr);
}
// AI: end
