#include "../http/NativeHttpServer.h"
#include "../output/RenderBuffer.h"

#include <cassert>
#include <cstring>
#include <filesystem>
#include <sstream>
#include <stdexcept>
#include <string>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>

#ifndef WLED_NATIVE_SOURCE_DIR
#define WLED_NATIVE_SOURCE_DIR "."
#endif

// AI: below section was generated by an AI
namespace {

class Socket {
public:
  explicit Socket(int fd) : _fd(fd) {}
  ~Socket() {
    if (_fd >= 0) close(_fd);
  }

  Socket(const Socket &) = delete;
  Socket &operator=(const Socket &) = delete;

  int fd() const { return _fd; }

private:
  int _fd;
};

Socket connectTo(uint16_t port) {
  const int fd = socket(AF_INET, SOCK_STREAM, 0);
  assert(fd >= 0);

  sockaddr_in address{};
  address.sin_family = AF_INET;
  address.sin_port = htons(port);
  address.sin_addr.s_addr = htonl(INADDR_LOOPBACK);

  assert(connect(fd, reinterpret_cast<sockaddr *>(&address), sizeof(address)) == 0);
  return Socket(fd);
}

std::string readAvailable(int fd) {
  std::string response;
  char buffer[4096];
  const ssize_t received = recv(fd, buffer, sizeof(buffer), 0);
  assert(received > 0);
  response.append(buffer, static_cast<size_t>(received));
  return response;
}

std::string readHttpHeaders(int fd) {
  std::string response;
  char c = '\0';
  while (response.find("\r\n\r\n") == std::string::npos) {
    assert(recv(fd, &c, 1, 0) == 1);
    response.push_back(c);
  }
  return response;
}

std::string httpRequest(uint16_t port, const std::string &request) {
  Socket socket = connectTo(port);
  assert(send(socket.fd(), request.data(), request.size(), 0) == static_cast<ssize_t>(request.size()));
  return readAvailable(socket.fd());
}

uint64_t fnv1a64(const std::string &value) {
  uint64_t hash = 14695981039346656037ULL;
  for (const unsigned char c : value) {
    hash ^= c;
    hash *= 1099511628211ULL;
  }
  return hash;
}

std::string maskedTextFrame(const std::string &payload) {
  std::string frame;
  frame.push_back(static_cast<char>(0x81));
  frame.push_back(static_cast<char>(0x80 | payload.size()));
  const uint8_t mask[4] = {0x12, 0x34, 0x56, 0x78};
  frame.append(reinterpret_cast<const char *>(mask), sizeof(mask));
  for (size_t i = 0; i < payload.size(); i++) frame.push_back(static_cast<char>(payload[i] ^ mask[i % 4]));
  return frame;
}

std::string readWebSocketText(int fd) {
  uint8_t header[2] = {};
  assert(recv(fd, header, sizeof(header), MSG_WAITALL) == 2);
  assert((header[0] & 0x0F) == 0x01);

  size_t length = header[1] & 0x7F;
  if (length == 126) {
    uint8_t extended[2] = {};
    assert(recv(fd, extended, sizeof(extended), MSG_WAITALL) == 2);
    length = (static_cast<size_t>(extended[0]) << 8) | extended[1];
  }

  std::string payload(length, '\0');
  assert(recv(fd, payload.data(), payload.size(), MSG_WAITALL) == static_cast<ssize_t>(payload.size()));
  return payload;
}

NativeHttpServer makeServer() {
  NativeHttpServerOptions options;
  options.host = "127.0.0.1";
  options.port = 0;
  options.webRoot = (std::filesystem::path(WLED_NATIVE_SOURCE_DIR) / "wled00" / "data").string();
  options.version = "test-version";
  options.nativeMac = "021122334455";

  NativeHttpServer server(options);
  assert(server.start());
  return server;
}

void testStaticRoutesAndJson() {
  NativeHttpServer server = makeServer();
  const uint16_t port = server.localPort();

  const std::string index = httpRequest(port, "GET / HTTP/1.1\r\nHost: localhost\r\n\r\n");
  assert(index.find("HTTP/1.1 200 OK") != std::string::npos);
  assert(index.find("<!DOCTYPE html>") != std::string::npos);

  const std::string settings = httpRequest(port, "GET /settings HTTP/1.1\r\nHost: localhost\r\n\r\n");
  assert(settings.find("HTTP/1.1 200 OK") != std::string::npos);
  assert(settings.find("settings") != std::string::npos || settings.find("Settings") != std::string::npos);

  const std::string json = httpRequest(port, "GET /json HTTP/1.1\r\nHost: localhost\r\n\r\n");
  assert(json.find("\"state\"") != std::string::npos);
  assert(json.find("\"info\"") != std::string::npos);
  assert(json.find("\"mac\":\"021122334455\"") != std::string::npos);

  const std::string version = httpRequest(port, "GET /version HTTP/1.1\r\nHost: localhost\r\n\r\n");
  assert(version.find("test-version") != std::string::npos);

  const std::string palettes = httpRequest(port, "GET /json/palettes HTTP/1.1\r\nHost: localhost\r\n\r\n");
  assert(palettes.find("\"0\"") != std::string::npos);
  assert(palettes.find("Default") != std::string::npos);

  const std::string fxdata = httpRequest(port, "GET /json/fxdata HTTP/1.1\r\nHost: localhost\r\n\r\n");
  assert(fxdata.find("HTTP/1.1 200 OK") != std::string::npos);
  assert(fxdata.find("[") != std::string::npos);

  const std::string settingsJs = httpRequest(port, "GET /settings/s.js?p=0 HTTP/1.1\r\nHost: localhost\r\n\r\n");
  assert(settingsJs.find("HTTP/1.1 200 OK") != std::string::npos);
  assert(settingsJs.find("native settings") != std::string::npos);
  assert(settingsJs.find("function GetV") != std::string::npos);

  const std::string upload = httpRequest(port, "POST /upload HTTP/1.1\r\nHost: localhost\r\nContent-Length: 0\r\n\r\n");
  assert(upload.find("501") != std::string::npos);
}

void testJsonPostUpdatesState() {
  NativeHttpServer server = makeServer();
  const uint16_t port = server.localPort();

  const std::string body = "{\"on\":false,\"bri\":42}";
  std::ostringstream request;
  request << "POST /json HTTP/1.1\r\nHost: localhost\r\nContent-Type: application/json\r\nContent-Length: "
          << body.size() << "\r\n\r\n" << body;
  const std::string posted = httpRequest(port, request.str());
  assert(posted.find("\"success\":true") != std::string::npos);

  const std::string state = httpRequest(port, "GET /json/state HTTP/1.1\r\nHost: localhost\r\n\r\n");
  assert(state.find("\"on\":false") != std::string::npos);
  assert(state.find("\"bri\":42") != std::string::npos);
}

void testWebSocketHandshakeAndStateMessages() {
  NativeHttpServer server = makeServer();
  Socket socket = connectTo(server.localPort());

  const std::string key = "dGhlIHNhbXBsZSBub25jZQ==";
  std::ostringstream handshake;
  handshake << "GET /ws HTTP/1.1\r\n"
            << "Host: localhost\r\n"
            << "Upgrade: websocket\r\n"
            << "Connection: Upgrade\r\n"
            << "Sec-WebSocket-Version: 13\r\n"
            << "Sec-WebSocket-Key: " << key << "\r\n\r\n";
  const std::string request = handshake.str();
  assert(send(socket.fd(), request.data(), request.size(), 0) == static_cast<ssize_t>(request.size()));

  const std::string response = readHttpHeaders(socket.fd());
  assert(response.find("HTTP/1.1 101 Switching Protocols") != std::string::npos);
  assert(response.find("Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=") != std::string::npos);

  const std::string initial = readWebSocketText(socket.fd());
  assert(initial.find("\"state\"") != std::string::npos);
  assert(initial.find("\"info\"") != std::string::npos);

  const std::string frame = maskedTextFrame("{\"v\":true}");
  assert(send(socket.fd(), frame.data(), frame.size(), 0) == static_cast<ssize_t>(frame.size()));

  const std::string verbose = readWebSocketText(socket.fd());
  assert(verbose.find("\"state\"") != std::string::npos);
  assert(fnv1a64(verbose) != 0);
}

} // namespace
// AI: end

int main() {
  testStaticRoutesAndJson();
  testJsonPostUpdatesState();
  testWebSocketHandshakeAndStateMessages();
  return 0;
}
