#include "../runtime/Runtime.h"

#include <cassert>
#include <chrono>
#include <filesystem>
#include <sstream>
#include <thread>

// AI: below section was generated by an AI
namespace {

void testLoopStopsAfterMaxIterations() {
  NativeRuntimeOptions options;
  options.maxLoopIterations = 3;
  options.loopDelayMs = 0;

  NativeRuntime runtime(options);
  const int exitCode = runtime.run();

  assert(exitCode == WLED_NATIVE_EXIT_OK);
  assert(runtime.loopIterations() == 3);
  assert(runtime.uptimeMs() >= 0);
}

void testStopRequestExitsCleanly() {
  NativeRuntimeOptions options;
  options.loopDelayMs = 1;

  NativeRuntime runtime(options);
  std::thread worker([&runtime]() {
    const int exitCode = runtime.run();
    assert(exitCode == WLED_NATIVE_EXIT_OK);
  });

  while (runtime.loopIterations() == 0) std::this_thread::sleep_for(std::chrono::milliseconds(1));
  runtime.requestStop();
  worker.join();

  assert(runtime.stopRequested());
}

void testRestartRequestUsesRestartExitCode() {
  NativeRuntimeOptions options;
  options.loopDelayMs = 1;

  NativeRuntime runtime(options);
  std::thread worker([&runtime]() {
    while (runtime.loopIterations() == 0) std::this_thread::sleep_for(std::chrono::milliseconds(1));
    runtime.requestRestart();
  });

  const int exitCode = runtime.run();
  worker.join();

  assert(exitCode == WLED_NATIVE_EXIT_RESTART);
  assert(runtime.restartRequested());
}

void testCliResolvesDefaultConfigDirFromEnvironment() {
  const std::filesystem::path root = std::filesystem::temp_directory_path() / "wled-native-config-env-test";
  setenv("WLED_CONFIG_DIR", root.string().c_str(), 1);

  char arg0[] = "wled-native";
  char *argv[] = {arg0};
  NativeCliResult result;
  std::ostringstream out;
  std::ostringstream err;

  assert(parseNativeCli(1, argv, result, out, err));
  assert(result.options.configDir == root.string());

  unsetenv("WLED_CONFIG_DIR");
}

} // namespace

int main() {
  testLoopStopsAfterMaxIterations();
  testStopRequestExitsCleanly();
  testRestartRequestUsesRestartExitCode();
  testCliResolvesDefaultConfigDirFromEnvironment();
  return 0;
}
// AI: end
