#include "../output/RenderBuffer.h"

#include <cassert>
#include <vector>

// AI: below section was generated by an AI
namespace {

void testRenderBufferStoresRgbwCctPixels() {
  NativeRenderBuffer buffer(3);
  assert(buffer.length() == 3);

  buffer.setPixel(1, NativeColor{10, 20, 30, 40, 2700});
  const NativeColor pixel = buffer.pixel(1);
  assert(pixel.r == 10);
  assert(pixel.g == 20);
  assert(pixel.b == 30);
  assert(pixel.w == 40);
  assert(pixel.cct == 2700);

  buffer.clear();
  assert(buffer.pixel(1).r == 0);
  assert(buffer.pixel(1).w == 0);
}

void testColorOrderEncoding() {
  NativeRenderBuffer buffer(1);
  buffer.setPixel(0, NativeColor{1, 2, 3, 4, 0});

  const std::vector<uint8_t> rgb = buffer.encode(NativeColorOrder::RGB);
  assert((rgb == std::vector<uint8_t>{1, 2, 3}));

  const std::vector<uint8_t> grb = buffer.encode(NativeColorOrder::GRB);
  assert((grb == std::vector<uint8_t>{2, 1, 3}));

  const std::vector<uint8_t> rgbw = buffer.encode(NativeColorOrder::RGBW);
  assert((rgbw == std::vector<uint8_t>{1, 2, 3, 4}));
}

void testEstimatedCurrentAndNullBackend() {
  NativeRenderBuffer buffer(2);
  buffer.setPixel(0, NativeColor{255, 0, 0, 0, 0});
  buffer.setPixel(1, NativeColor{0, 255, 0, 255, 0});
  assert(buffer.estimatedCurrentMilliamps() == 60);

  NativeNullOutputBackend backend;
  assert(backend.begin(buffer.length()));
  assert(backend.show(buffer));
  assert(backend.frameCount() == 1);
  assert(backend.lastFrame().size() == 2);
  assert(backend.lastFrame()[1].g == 255);
}

void testOutOfRangePixelsAreIgnored() {
  NativeRenderBuffer buffer(1);
  buffer.setPixel(4, NativeColor{255, 255, 255, 255, 0});
  assert(buffer.pixel(0).r == 0);
  assert(buffer.pixel(4).r == 0);
}

} // namespace
// AI: end

int main() {
  testRenderBufferStoresRgbwCctPixels();
  testColorOrderEncoding();
  testEstimatedCurrentAndNullBackend();
  testOutOfRangePixelsAreIgnored();
  return 0;
}
