#include "../net/Network.h"

#include <cassert>
#include <chrono>
#include <filesystem>
#include <string>
#include <thread>

// AI: below section was generated by an AI
namespace {

void testStableNativeIdentity() {
  const std::filesystem::path root = std::filesystem::temp_directory_path() / "wled-native-identity-test";
  std::filesystem::remove_all(root);

  NativeIdentityStore first(root.string());
  const std::string mac = first.loadOrCreateMac();
  assert(NativeIdentityStore::isValidMac(mac));
  assert(mac.substr(0, 2) == "02");

  NativeIdentityStore second(root.string());
  assert(second.loadOrCreateMac() == mac);

  std::filesystem::remove_all(root);
}

void testDnsResolution() {
  IPAddress localhost;
  assert(resolveHostname("localhost", localhost));
  assert(localhost != IPAddress());
}

void testInterfaceDiscoveryFindsLoopback() {
  const std::vector<NativeNetworkInterface> interfaces = listNetworkInterfaces();
  bool foundLoopback = false;
  for (const NativeNetworkInterface &iface : interfaces) {
    if (iface.loopback && iface.address != IPAddress()) foundLoopback = true;
  }

  assert(foundLoopback);
}

void testUdpLoopback() {
  NativeUdpSocket socket;
  assert(socket.bind(IPAddress(127, 0, 0, 1), 0));
  assert(socket.localPort() > 0);

  const std::string payload = "wled";
  assert(socket.sendTo(reinterpret_cast<const uint8_t *>(payload.data()), payload.size(), IPAddress(127, 0, 0, 1), socket.localPort()) == payload.size());

  uint8_t buffer[16] = {};
  IPAddress remoteAddress;
  uint16_t remotePort = 0;
  const int received = socket.receive(buffer, sizeof(buffer), remoteAddress, remotePort, 1000);

  assert(received == static_cast<int>(payload.size()));
  assert(std::string(reinterpret_cast<char *>(buffer), received) == payload);
  assert(remoteAddress == IPAddress(127, 0, 0, 1));
  assert(remotePort > 0);
}

} // namespace

int main() {
  testStableNativeIdentity();
  testDnsResolution();
  testInterfaceDiscoveryFindsLoopback();
  testUdpLoopback();
  return 0;
}
// AI: end
