#include "../runtime/Runtime.h"
#include "../runtime/SignalHandling.h"

#include <cassert>
#include <csignal>

// AI: below section was generated by an AI
int main() {
  NativeRuntimeOptions options;
  options.loopDelayMs = 1;

  NativeRuntime runtime(options);
  NativeSignalHandler signals(runtime);

  assert(signals.install());
  std::raise(SIGTERM);

  const int exitCode = runtime.run();
  signals.restore();

  assert(exitCode == WLED_NATIVE_EXIT_OK);
  assert(runtime.stopRequested());
  return 0;
}
// AI: end
