#include "../core/NativeWledCore.h"

#include <cassert>
#include <filesystem>
#include <fstream>

// AI: below section was generated by an AI
namespace {

std::filesystem::path tempRoot(const char *name) {
  const std::filesystem::path root = std::filesystem::temp_directory_path() / name;
  std::error_code error;
  std::filesystem::remove_all(root, error);
  std::filesystem::create_directories(root, error);
  return root;
}

void testJsonStateUpdatesRenderBuffer() {
  const std::filesystem::path root = tempRoot("wled-native-core-state");
  NativeWledCore core(root);
  NativeRenderBuffer buffer(12);
  core.begin(buffer.length(), 1000);

  core.applyJsonState("{\"bri\":200,\"seg\":[{\"id\":0,\"fx\":9,\"pal\":11,\"col\":[[255,0,0],[0,0,0],[0,0,0]]}]}", 1000);
  core.render(buffer, 1200);

  assert(buffer.hasVisiblePixels());
  assert(core.jsonState(1200).find("\"fx\":9") != std::string::npos);
  assert(core.jsonEffects().find("Rainbow") != std::string::npos);
  assert(core.jsonPalettes().find("Rainbow") != std::string::npos);
}

void testPresetSaveAndApply() {
  const std::filesystem::path root = tempRoot("wled-native-core-preset");
  NativeWledCore core(root);
  NativeRenderBuffer buffer(8);
  core.begin(buffer.length(), 0);

  core.applyJsonState("{\"bri\":77,\"seg\":[{\"id\":0,\"fx\":46,\"pal\":9}]}", 0);
  assert(core.savePreset(3));

  core.applyJsonState("{\"bri\":10,\"seg\":[{\"id\":0,\"fx\":0,\"pal\":0}]}", 10);
  assert(core.applyPreset(3, 20));

  const std::string state = core.jsonState(20);
  assert(state.find("\"bri\":77") != std::string::npos);
  assert(state.find("\"fx\":46") != std::string::npos);
  assert(core.presetsJson().find("\"3\"") != std::string::npos);
}

void testPlaylistAdvancesPresets() {
  const std::filesystem::path root = tempRoot("wled-native-core-playlist");
  {
    std::ofstream presets(root / "presets.json");
    presets << "{\"0\":{},"
            << "\"1\":{\"n\":\"One\",\"bri\":40,\"seg\":[{\"id\":0,\"fx\":0,\"col\":[[255,0,0],[0,0,0],[0,0,0]]}]},"
            << "\"2\":{\"n\":\"Two\",\"bri\":90,\"seg\":[{\"id\":0,\"fx\":9,\"pal\":11}]},"
            << "\"5\":{\"n\":\"List\",\"playlist\":{\"ps\":[1,2],\"dur\":[1,1],\"transition\":[0,0],\"repeat\":1}}}";
  }

  NativeWledCore core(root);
  NativeRenderBuffer buffer(8);
  core.begin(buffer.length(), 0);
  assert(core.applyPreset(5, 0));
  assert(core.jsonState(0).find("\"ps\":1") != std::string::npos);

  core.tick(150);
  assert(core.jsonState(150).find("\"ps\":2") != std::string::npos);

  core.render(buffer, 150);
  assert(buffer.hasVisiblePixels());
}

void testNightlightFadesBrightness() {
  const std::filesystem::path root = tempRoot("wled-native-core-nightlight");
  NativeWledCore core(root);
  NativeRenderBuffer buffer(4);
  core.begin(buffer.length(), 0);
  core.applyJsonState("{\"bri\":200,\"nl\":{\"on\":true,\"dur\":1,\"tbri\":20,\"mode\":1}}", 0);

  const std::string middle = core.jsonState(30000);
  assert(middle.find("\"bri\":110") != std::string::npos);

  core.tick(61000);
  const std::string done = core.jsonState(61000);
  assert(done.find("\"bri\":20") != std::string::npos);
  assert(done.find("\"on\":false") != std::string::npos || done.find("\"on\":true") != std::string::npos);
}

} // namespace
// AI: end

int main() {
  testJsonStateUpdatesRenderBuffer();
  testPresetSaveAndApply();
  testPlaylistAdvancesPresets();
  testNightlightFadesBrightness();
  return 0;
}

