#include "Runtime.h"

#include "SignalHandling.h"
#include "../arduino_compat/Arduino.h"
#include "../net/Network.h"

#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <thread>

#ifndef WLED_NATIVE_VERSION
#define WLED_NATIVE_VERSION "dev"
#endif

// AI: below section was generated by an AI
namespace {

bool readValue(int argc, char **argv, int &index, const char *name, std::string &value, std::ostream &err) {
  if (index + 1 >= argc) {
    err << "Missing value for " << name << "\n";
    return false;
  }

  value = argv[++index];
  return true;
}

bool parseUnsigned(const std::string &value, unsigned long min, unsigned long max, unsigned long &parsed) {
  char *end = nullptr;
  const unsigned long candidate = std::strtoul(value.c_str(), &end, 10);
  if (end == value.c_str() || *end != '\0' || candidate < min || candidate > max) return false;

  parsed = candidate;
  return true;
}

std::string defaultConfigDir() {
  const char *overrideDir = std::getenv("WLED_CONFIG_DIR");
  if (overrideDir != nullptr && overrideDir[0] != '\0') return overrideDir;

  const char *home = std::getenv("HOME");
#if defined(__APPLE__)
  if (home != nullptr && home[0] != '\0') {
    return (std::filesystem::path(home) / "Library" / "Application Support" / "WLED").string();
  }
#else
  const char *xdgConfigHome = std::getenv("XDG_CONFIG_HOME");
  if (xdgConfigHome != nullptr && xdgConfigHome[0] != '\0') {
    return (std::filesystem::path(xdgConfigHome) / "wled").string();
  }
  if (home != nullptr && home[0] != '\0') {
    return (std::filesystem::path(home) / ".config" / "wled").string();
  }
#endif

  return ".wled-native";
}

} // namespace

NativeRuntime::NativeRuntime(const NativeRuntimeOptions &options) : _options(options) {
}

// Initializes the current native lifecycle skeleton before HTTP/config/server services exist.
void NativeRuntime::setup() {
  _startMs = millis();
  NativeIdentityStore identity(_options.configDir);
  const std::string nativeMac = identity.loadOrCreateMac();

  std::cout << "WLED native runtime starting\n"
            << "host=" << _options.host << "\n"
            << "port=" << _options.port << "\n"
            << "logLevel=" << _options.logLevel << "\n"
            << "configDir=" << _options.configDir << "\n"
            << "nativeMac=" << nativeMac << "\n";
}

// Preserves the Arduino loop shape so WLED work can move into this scheduler incrementally.
void NativeRuntime::loopOnce() {
  _loopIterations++;
}

int NativeRuntime::run() {
  setup();

  while (!stopRequested() && !restartRequested()) {
    if (nativeSignalStopRequested()) requestStop();
    if (stopRequested()) break;

    loopOnce();

    if (_options.maxLoopIterations > 0 && loopIterations() >= _options.maxLoopIterations) requestStop();
    if (_options.durationMs > 0 && uptimeMs() >= _options.durationMs) requestStop();
    if (stopRequested() || restartRequested()) break;

    if (_options.loopDelayMs > 0) std::this_thread::sleep_for(std::chrono::milliseconds(_options.loopDelayMs));
    else yield();
  }

  std::cout << "WLED native runtime stopping\n"
            << "uptimeMs=" << uptimeMs() << "\n"
            << "loopIterations=" << loopIterations() << "\n";

  return restartRequested() ? WLED_NATIVE_EXIT_RESTART : WLED_NATIVE_EXIT_OK;
}

void NativeRuntime::requestStop() {
  _stopRequested.store(true);
}

void NativeRuntime::requestRestart() {
  _restartRequested.store(true);
}

bool NativeRuntime::stopRequested() const {
  return _stopRequested.load();
}

bool NativeRuntime::restartRequested() const {
  return _restartRequested.load();
}

uint64_t NativeRuntime::loopIterations() const {
  return _loopIterations.load();
}

uint64_t NativeRuntime::uptimeMs() const {
  if (_startMs == 0) return 0;

  return millis() - _startMs;
}

void printNativeHelp(std::ostream &out) {
  out << "WLED native runtime\n"
      << "\n"
      << "Usage: wled-native [options]\n"
      << "\n"
      << "Options:\n"
      << "  --help                 Show this help text and exit\n"
      << "  --version              Show the WLED version and exit\n"
      << "  --config-dir <path>    Native config root\n"
      << "  --host <address>       Bind address placeholder (default: 127.0.0.1)\n"
      << "  --port <port>          HTTP port placeholder (default: 8080)\n"
      << "  --log-level <level>    Runtime log level placeholder (default: info)\n"
      << "  --duration-ms <ms>     Stop after a duration, for tests and scripts\n"
      << "  --max-loops <count>    Stop after loop iterations, for tests and scripts\n";
}

void printNativeVersion(std::ostream &out) {
  out << "WLED " << WLED_NATIVE_VERSION << " (wled-native)\n";
}

// Parses stable CLI options before the native HTTP/config services are connected.
bool parseNativeCli(int argc, char **argv, NativeCliResult &result, std::ostream &out, std::ostream &err) {
  result = NativeCliResult{};

  for (int i = 1; i < argc; i++) {
    const std::string arg = argv[i];
    if (arg == "--help" || arg == "-h") {
      printNativeHelp(out);
      result.ok = true;
      result.exitNow = true;
      return true;
    }
    if (arg == "--version") {
      printNativeVersion(out);
      result.ok = true;
      result.exitNow = true;
      return true;
    }
    if (arg == "--config-dir") {
      if (!readValue(argc, argv, i, "--config-dir", result.options.configDir, err)) return false;
    } else if (arg == "--host") {
      if (!readValue(argc, argv, i, "--host", result.options.host, err)) return false;
    } else if (arg == "--port") {
      std::string value;
      unsigned long parsed = 0;
      if (!readValue(argc, argv, i, "--port", value, err)) return false;
      if (!parseUnsigned(value, 1, 65535, parsed)) {
        err << "Invalid value for --port: " << value << "\n";
        return false;
      }
      result.options.port = static_cast<uint16_t>(parsed);
    } else if (arg == "--log-level") {
      if (!readValue(argc, argv, i, "--log-level", result.options.logLevel, err)) return false;
    } else if (arg == "--duration-ms") {
      std::string value;
      unsigned long parsed = 0;
      if (!readValue(argc, argv, i, "--duration-ms", value, err)) return false;
      if (!parseUnsigned(value, 1, 86400000, parsed)) {
        err << "Invalid value for --duration-ms: " << value << "\n";
        return false;
      }
      result.options.durationMs = parsed;
    } else if (arg == "--max-loops") {
      std::string value;
      unsigned long parsed = 0;
      if (!readValue(argc, argv, i, "--max-loops", value, err)) return false;
      if (!parseUnsigned(value, 1, 100000000, parsed)) {
        err << "Invalid value for --max-loops: " << value << "\n";
        return false;
      }
      result.options.maxLoopIterations = parsed;
    } else {
      err << "Unknown option: " << arg << "\n";
      return false;
    }
  }

  result.ok = true;
  if (result.options.configDir.empty()) result.options.configDir = defaultConfigDir();
  return true;
}
// AI: end
