#include "SignalHandling.h"

#include "Runtime.h"

#include <csignal>
#include <cstring>

#if defined(__unix__) || defined(__APPLE__)
#include <signal.h>
#endif

// AI: below section was generated by an AI
namespace {

volatile sig_atomic_t pendingStopSignal = 0;

#if defined(__unix__) || defined(__APPLE__)
struct sigaction previousIntAction;
struct sigaction previousTermAction;
#endif

void handleStopSignal(int) {
  pendingStopSignal = 1;
}

} // namespace

NativeSignalHandler::NativeSignalHandler(NativeRuntime &runtime) : _runtime(runtime) {
}

NativeSignalHandler::~NativeSignalHandler() {
  restore();
}

// Installs SIGINT/SIGTERM handlers that only set a signal-safe pending flag.
bool NativeSignalHandler::install() {
  nativeResetSignalState();

#if defined(__unix__) || defined(__APPLE__)
  struct sigaction action;
  std::memset(&action, 0, sizeof(action));
  action.sa_handler = handleStopSignal;
  sigemptyset(&action.sa_mask);

  if (sigaction(SIGINT, &action, &previousIntAction) != 0) return false;
  if (sigaction(SIGTERM, &action, &previousTermAction) != 0) {
    sigaction(SIGINT, &previousIntAction, nullptr);
    return false;
  }

  _installed = true;
  return true;
#else
  return false;
#endif
}

void NativeSignalHandler::restore() {
  if (!_installed) return;

#if defined(__unix__) || defined(__APPLE__)
  sigaction(SIGINT, &previousIntAction, nullptr);
  sigaction(SIGTERM, &previousTermAction, nullptr);
#endif

  _runtime.requestStop();
  _installed = false;
}

bool nativeSignalStopRequested() {
  return pendingStopSignal != 0;
}

void nativeResetSignalState() {
  pendingStopSignal = 0;
}
// AI: end
